In [6]:
import sys
sys.path.insert(0, r"C:\CYME\CYME")
import cympy

from datetime import datetime
import csv
import os
import math
import copy
import re
import decimal
import logging

def run_cyme(sxrt):

    
    print("Opening: ", sxrt)
    cympy.study.Open(sxrt)

    # ---------------------------------------------------------------------------
    # Load Flow — all active controls disabled
    # ---------------------------------------------------------------------------
    lf = cympy.sim.LoadFlow()

    # --- General solver settings ------------------------------------------------
    lf.SetValue(0.001,  'ParametersConfigurations[0].VoltageTolerance')
    lf.SetValue("VoltageDropUnbalanced", 'ParametersConfigurations[0].AnalysisMode')

    # Source / line modelling
    lf.SetValue(0, 'ParametersConfigurations[0].IncludeSourceImpedance')
    lf.SetValue(0, 'ParametersConfigurations[0].IncludeLineCharging')
    lf.SetValue(0, 'ParametersConfigurations[0].AssumeLineTransposition')

    # Temperature adjustment off
    lf.SetValue(0, 'ParametersConfigurations[0].TemperatureAdjustment.EnableTemperatureAdjustment')

    # Voltage-sensitivity load model
    lf.SetValue('Global', 'ParametersConfigurations[0].LoadFlowVoltageSensitivityLoadModel.Mode')
    lf.SetValue(0.0,     'ParametersConfigurations[0].LoadFlowVoltageSensitivityLoadModel.V')

    # --- Lock regulators / switched shunts (prevents tap & stage changes) -------
    lf.SetValue(1, 'ParametersConfigurations[0].LockMultiStageSwitchableShunts')
    lf.SetValue(1, 'ParametersConfigurations[0].LockSwitchedCapacitors')

    # --- Equipment status: disable ALL active controls --------------------------
    # Switched capacitor control modes — all OFF
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.VoltageCapStatus')
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.CurrentCapStatus')
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.ReactiveCurrentCapStatus')
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.PowerFactorCapStatus')
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.TemperatureCapStatus')
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.TimeCapStatus')
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.KVARCapStatus')
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.PythonScriptCapStatus')

    # Fixed caps remain on (they have no switching logic)
    lf.SetValue(1, 'ParametersConfigurations[0].EquipmentStatusParameters.FixedCapStatus')

    # Multi-stage switchable shunts — OFF
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.MultiStageSwitchableShuntStatus')

    # SVCs / VAR compensators — OFF
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.SVCStatus')
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.VARCompensatorStatus')

    # Motors — OFF
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.SynchronousMotorStatus')
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.InductionMotorStatus')

    # Generators — keep synchronous & ECG energised but all others OFF
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.GeneratorStatus')
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.SynchronousGeneratorStatus')
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.InductionGeneratorStatus')
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.ElectronicallyCoupledGeneratorStatus')

    # Renewables / storage — OFF
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.WecsStatus')
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.BESSStatus')
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.SofcStatus')
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.PhotovoltaicStatus')
    lf.SetValue(0, 'ParametersConfigurations[0].EquipmentStatusParameters.MicroTurbineStatus')

    # --- Run load flow -----------------------------------------------------------
    lf.Run()
    print("Load flow complete (all active controls disabled)")

In [2]:
import pandas as pd

df = pd.read_csv(rf"c:\Users\fgonzales\git\mc-0.0.1.15\scripts\encoded - Copy.csv")

In [12]:
import numpy as np
import pandas as pd

def _safe_float(val):
    """Convert a CYME query result to float, returning None for empty/invalid strings."""
    if val is None or (isinstance(val, str) and val.strip() == ''):
        return None
    return float(val)

def _get_cyme_v_pu(sxst_file):
    """Run CYME load flow and return a DataFrame with NODE_ID, VA, VB, VC (pu)."""
    import sys
    sys.path.insert(0, r"C:\CYME\CYME")
    import cympy

    PRECISION = 7
    nodes = cympy.study.ListNodes(cympy.enums.NodeType.All)
    rows = []
    for node in nodes:
        nid = node.ID
        rows.append({
            'NODE_ID': nid,
            'VA_CYME': _safe_float(cympy.study.QueryInfoNode('VpuA', nid, PRECISION)),
            'VB_CYME': _safe_float(cympy.study.QueryInfoNode('VpuB', nid, PRECISION)),
            'VC_CYME': _safe_float(cympy.study.QueryInfoNode('VpuC', nid, PRECISION)),
        })
    return pd.DataFrame(rows)


def _get_mc_v_pu(net):
    """Extract per-bus VA, VB, VC (pu) from a solved MC net. Returns a DataFrame."""
    bus_indices = net.bus.index.get_level_values(0).unique()
    rows = []
    for bus_idx in bus_indices:
        bus_data = net.bus.loc[bus_idx]
        name = bus_data['name'].iloc[0] if isinstance(bus_data, pd.DataFrame) else bus_data['name']
        v = {}
        for phase, label in [(1, 'VA_MC'), (2, 'VB_MC'), (3, 'VC_MC')]:
            if (bus_idx, phase) in net.res_bus.index:
                vm = float(net.res_bus.loc[(bus_idx, phase), 'vm_pu'])
                v[label] = vm if not np.isnan(vm) else None
            else:
                v[label] = None
        rows.append({'NODE_ID': name, **v})
    return pd.DataFrame(rows)


def compare_mc_cyme(net, sxst_file):
    """Run both engines, compute network-wide mean v_pu independently (no node matching)."""
    from multiconductor.pycci.cci_powerflow import run_pf

    # Query CYME results (study already open)
    df_cyme = _get_cyme_v_pu(sxst_file)
    for c in ['VA_CYME', 'VB_CYME', 'VC_CYME']:
        df_cyme[c] = pd.to_numeric(df_cyme[c], errors='coerce')
    df_cyme = df_cyme.dropna(subset=['VA_CYME', 'VB_CYME', 'VC_CYME'])

    # Run MC
    run_pf(net, tol_vang_rad=1e-5, tol_vmag_pu=1e-5)
    df_mc = _get_mc_v_pu(net)
    for c in ['VA_MC', 'VB_MC', 'VC_MC']:
        df_mc[c] = pd.to_numeric(df_mc[c], errors='coerce')
    df_mc = df_mc.dropna(subset=['VA_MC', 'VB_MC', 'VC_MC'])

    summary = {
        'VA_MC_mean':   df_mc['VA_MC'].mean(),
        'VB_MC_mean':   df_mc['VB_MC'].mean(),
        'VC_MC_mean':   df_mc['VC_MC'].mean(),
        'MC_node_count': len(df_mc),
        'VA_CYME_mean': df_cyme['VA_CYME'].mean(),
        'VB_CYME_mean': df_cyme['VB_CYME'].mean(),
        'VC_CYME_mean': df_cyme['VC_CYME'].mean(),
        'CYME_node_count': len(df_cyme),
    }
    return summary

In [13]:
def run_circuit(circuit_key):
    import pickle
    from pathlib import Path

    print(f"Processing {circuit_key}...")
    pkl_file = Path(rf"c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\{circuit_key}.pkl")
    sxst_file = Path(rf"c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\{circuit_key}.sxst")

    # Run CYME load flow first (opens study, keeps it open for querying)
    run_cyme(str(sxst_file))

    with open(pkl_file, 'rb') as fh:
        net = pickle.load(fh)

    summary = compare_mc_cyme(net, str(sxst_file))

    # Close the CYME study after results have been queried
    cympy.study.Close(AskForSave=False)

    summary['CKT_KEY'] = circuit_key
    print(f"  {circuit_key}: MC nodes={summary['MC_node_count']} CYME nodes={summary['CYME_node_count']}, "
          f"VA mean MC={summary['VA_MC_mean']:.5f} CYME={summary['VA_CYME_mean']:.5f}")
    return summary

In [14]:
all_summaries = []
for circuit_key in df['CIRCUIT_KEY']:
    try:
        summary = run_circuit(circuit_key)
        all_summaries.append(summary)
    except Exception as e:
        print(f"Error running circuit {circuit_key}: {e}")

summary_df = pd.DataFrame(all_summaries)
summary_df

Processing CKT_2155_12331...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_2155_12331.sxst
Load flow complete (all active controls disabled)
  CKT_2155_12331: MC nodes=719 CYME nodes=619, VA mean MC=0.94993 CYME=1.00550
Processing CKT_3250_02485...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_3250_02485.sxst
Load flow complete (all active controls disabled)
  CKT_3250_02485: MC nodes=1399 CYME nodes=998, VA mean MC=1.01167 CYME=1.01173
Processing CKT_156_06131...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_156_06131.sxst
Load flow complete (all active controls disabled)
  CKT_156_06131: MC nodes=479 CYME nodes=473, VA mean MC=0.98987 CYME=1.00306
Processing CKT_209_14375...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_209_14375.sxst
Load flow complete (all active controls disabled)
  CKT_209_14375: MC nodes=829 CYME nodes=782, VA mean MC=0.96746 CYME=0.96380
Processing CKT_1727_14043...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1727_14043.sxst
Load flow complete (all active controls disabled)
  CKT_1727_14043: MC nodes=763 CYME nodes=699, VA mean MC=1.09005 CYME=1.00482
Processing CKT_1747_14145...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1747_14145.sxst
Error running circuit CKT_1747_14145: Unable to open file : c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1747_14145.sxst
Processing CKT_4372_05219...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_4372_05219.sxst
Load flow complete (all active controls disabled)
  CKT_4372_05219: MC nodes=510 CYME nodes=496, VA mean MC=1.00104 CYME=1.01335
Processing CKT_1051_12960...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1051_12960.sxst
Load flow complete (all active controls disabled)
  CKT_1051_12960: MC nodes=1260 CYME nodes=1094, VA mean MC=0.99906 CYME=1.02954
Processing CKT_3953_09972...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_3953_09972.sxst
Load flow complete (all active controls disabled)
  CKT_3953_09972: MC nodes=407 CYME nodes=379, VA mean MC=0.99277 CYME=1.00238
Processing CKT_4337_10933...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_4337_10933.sxst
Load flow complete (all active controls disabled)
  CKT_4337_10933: MC nodes=358 CYME nodes=358, VA mean MC=0.99647 CYME=1.02910
Processing CKT_4186_02037...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_4186_02037.sxst
Load flow complete (all active controls disabled)
  CKT_4186_02037: MC nodes=248 CYME nodes=248, VA mean MC=0.99696 CYME=1.00648
Processing CKT_2751_02720...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_2751_02720.sxst
Load flow complete (all active controls disabled)
  CKT_2751_02720: MC nodes=1005 CYME nodes=761, VA mean MC=0.93762 CYME=1.00576
Processing CKT_247_16926...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_247_16926.sxst
Load flow complete (all active controls disabled)
  CKT_247_16926: MC nodes=259 CYME nodes=259, VA mean MC=1.00727 CYME=1.00439
Processing CKT_4365_16974...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_4365_16974.sxst
Load flow complete (all active controls disabled)
  CKT_4365_16974: MC nodes=777 CYME nodes=777, VA mean MC=0.98978 CYME=1.00625
Processing CKT_4868_03943...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_4868_03943.sxst
Load flow complete (all active controls disabled)
  CKT_4868_03943: MC nodes=194 CYME nodes=193, VA mean MC=0.99794 CYME=1.00325
Processing CKT_9005_13663...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_9005_13663.sxst
Load flow complete (all active controls disabled)
  CKT_9005_13663: MC nodes=725 CYME nodes=725, VA mean MC=0.99888 CYME=1.00286
Processing CKT_4338_05488...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_4338_05488.sxst
Load flow complete (all active controls disabled)
  CKT_4338_05488: MC nodes=223 CYME nodes=223, VA mean MC=1.00030 CYME=1.00404
Processing CKT_4330_12571...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_4330_12571.sxst
Load flow complete (all active controls disabled)
  CKT_4330_12571: MC nodes=691 CYME nodes=515, VA mean MC=0.91968 CYME=1.00449
Processing CKT_3024_07660...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_3024_07660.sxst
Load flow complete (all active controls disabled)
  CKT_3024_07660: MC nodes=1419 CYME nodes=1271, VA mean MC=0.95464 CYME=0.96875
Processing CKT_361_15376...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_361_15376.sxst
Load flow complete (all active controls disabled)
  CKT_361_15376: MC nodes=325 CYME nodes=325, VA mean MC=1.00507 CYME=1.00277
Processing CKT_2465_10435...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_2465_10435.sxst
Load flow complete (all active controls disabled)
  CKT_2465_10435: MC nodes=300 CYME nodes=300, VA mean MC=0.99727 CYME=0.96838
Processing CKT_3986_04130...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_3986_04130.sxst
Load flow complete (all active controls disabled)
  CKT_3986_04130: MC nodes=617 CYME nodes=539, VA mean MC=0.93888 CYME=1.01501
Processing CKT_5254_06448...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_5254_06448.sxst
Load flow complete (all active controls disabled)
  CKT_5254_06448: MC nodes=417 CYME nodes=417, VA mean MC=1.01230 CYME=1.00319
Processing CKT_2574_07870...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_2574_07870.sxst
Load flow complete (all active controls disabled)
  CKT_2574_07870: MC nodes=810 CYME nodes=804, VA mean MC=0.96675 CYME=0.95116
Processing CKT_3265_05123...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_3265_05123.sxst
Error running circuit CKT_3265_05123: Unable to open file : c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_3265_05123.sxst
Processing CKT_1043_18094...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1043_18094.sxst
Error running circuit CKT_1043_18094: Unable to open file : c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1043_18094.sxst
Processing CKT_3796_06549...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_3796_06549.sxst
Load flow complete (all active controls disabled)
  CKT_3796_06549: MC nodes=1328 CYME nodes=962, VA mean MC=1.58914 CYME=1.00391
Processing CKT_2839_03328...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_2839_03328.sxst
Load flow complete (all active controls disabled)
  CKT_2839_03328: MC nodes=1759 CYME nodes=1703, VA mean MC=0.94639 CYME=0.96859
Processing CKT_6074_00727...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_6074_00727.sxst
Load flow complete (all active controls disabled)
  CKT_6074_00727: MC nodes=864 CYME nodes=829, VA mean MC=0.99663 CYME=1.01942
Processing CKT_2403_05307...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_2403_05307.sxst
Load flow complete (all active controls disabled)
  CKT_2403_05307: MC nodes=721 CYME nodes=699, VA mean MC=0.97588 CYME=1.00740
Processing CKT_1393_13655...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1393_13655.sxst
Error running circuit CKT_1393_13655: Unable to open file : c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1393_13655.sxst
Processing CKT_237_16860...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_237_16860.sxst
Error running circuit CKT_237_16860: Unable to open file : c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_237_16860.sxst
Processing CKT_911_17870...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_911_17870.sxst
Load flow complete (all active controls disabled)
  CKT_911_17870: MC nodes=1353 CYME nodes=1325, VA mean MC=0.98721 CYME=1.01397
Processing CKT_2443_03688...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_2443_03688.sxst
Load flow complete (all active controls disabled)
  CKT_2443_03688: MC nodes=678 CYME nodes=542, VA mean MC=0.88857 CYME=1.01123
Processing CKT_1962_01050...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1962_01050.sxst
Load flow complete (all active controls disabled)
  CKT_1962_01050: MC nodes=423 CYME nodes=421, VA mean MC=0.99177 CYME=0.84960
Processing CKT_3401_02768...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_3401_02768.sxst
Load flow complete (all active controls disabled)
  CKT_3401_02768: MC nodes=418 CYME nodes=344, VA mean MC=0.93337 CYME=1.00342
Processing CKT_1883_00600...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1883_00600.sxst
Error running circuit CKT_1883_00600: Unable to open file : c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1883_00600.sxst
Processing CKT_1581_18950...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1581_18950.sxst
Load flow complete (all active controls disabled)
  CKT_1581_18950: MC nodes=562 CYME nodes=562, VA mean MC=0.99382 CYME=1.00662
Processing CKT_5777_03296...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_5777_03296.sxst
Error running circuit CKT_5777_03296: Unable to open file : c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_5777_03296.sxst
Processing CKT_3675_06230...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_3675_06230.sxst
Load flow complete (all active controls disabled)
  CKT_3675_06230: MC nodes=516 CYME nodes=516, VA mean MC=0.97585 CYME=1.00744
Processing CKT_3080_07928...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_3080_07928.sxst
Load flow complete (all active controls disabled)
  CKT_3080_07928: MC nodes=906 CYME nodes=814, VA mean MC=0.97563 CYME=0.97561
Processing CKT_2404_07490...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_2404_07490.sxst
Load flow complete (all active controls disabled)
  CKT_2404_07490: MC nodes=1232 CYME nodes=1125, VA mean MC=0.97113 CYME=1.02402
Processing CKT_1896_00669...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1896_00669.sxst
Load flow complete (all active controls disabled)
  CKT_1896_00669: MC nodes=1062 CYME nodes=954, VA mean MC=0.95774 CYME=0.82262
Processing CKT_1893_00663...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1893_00663.sxst
Error running circuit CKT_1893_00663: Unable to open file : c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1893_00663.sxst
Processing CKT_1547_16352...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1547_16352.sxst
Load flow complete (all active controls disabled)
  CKT_1547_16352: MC nodes=369 CYME nodes=354, VA mean MC=0.98688 CYME=1.00465
Processing CKT_1824_19417...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1824_19417.sxst
Load flow complete (all active controls disabled)
  CKT_1824_19417: MC nodes=738 CYME nodes=688, VA mean MC=0.96334 CYME=1.03181
Processing CKT_2500_08194...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_2500_08194.sxst
Load flow complete (all active controls disabled)
  CKT_2500_08194: MC nodes=804 CYME nodes=773, VA mean MC=0.98284 CYME=1.03025
Processing CKT_4854_12781...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_4854_12781.sxst
Load flow complete (all active controls disabled)
  CKT_4854_12781: MC nodes=671 CYME nodes=593, VA mean MC=0.96636 CYME=1.00383
Processing CKT_3058_03460...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_3058_03460.sxst
Load flow complete (all active controls disabled)
  CKT_3058_03460: MC nodes=777 CYME nodes=734, VA mean MC=0.97707 CYME=0.97024
Processing CKT_5902_19838...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_5902_19838.sxst
Load flow complete (all active controls disabled)
  CKT_5902_19838: MC nodes=323 CYME nodes=322, VA mean MC=0.99375 CYME=1.00608
Processing CKT_4800_10687...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_4800_10687.sxst
Load flow complete (all active controls disabled)
  CKT_4800_10687: MC nodes=225 CYME nodes=223, VA mean MC=0.99819 CYME=1.00193
Processing CKT_1419_16122...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1419_16122.sxst
Load flow complete (all active controls disabled)
  CKT_1419_16122: MC nodes=125 CYME nodes=124, VA mean MC=1.06070 CYME=1.03885
Processing CKT_2053_00870...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_2053_00870.sxst
Load flow complete (all active controls disabled)
  CKT_2053_00870: MC nodes=672 CYME nodes=652, VA mean MC=0.99501 CYME=1.00439
Processing CKT_3092_06357...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_3092_06357.sxst
Load flow complete (all active controls disabled)
  CKT_3092_06357: MC nodes=821 CYME nodes=761, VA mean MC=1.25701 CYME=1.02577
Processing CKT_435_17253...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_435_17253.sxst
Load flow complete (all active controls disabled)
  CKT_435_17253: MC nodes=594 CYME nodes=539, VA mean MC=1.29777 CYME=1.00291
Processing CKT_2543_03584...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_2543_03584.sxst
Load flow complete (all active controls disabled)
  CKT_2543_03584: MC nodes=1007 CYME nodes=1004, VA mean MC=8.73175 CYME=1.05585
Processing CKT_2947_06280...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_2947_06280.sxst
Load flow complete (all active controls disabled)
  CKT_2947_06280: MC nodes=462 CYME nodes=447, VA mean MC=1.00345 CYME=1.00421
Processing CKT_4176_01945...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_4176_01945.sxst
Error running circuit CKT_4176_01945: Unable to open file : c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_4176_01945.sxst
Processing CKT_2120_12131...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_2120_12131.sxst
Load flow complete (all active controls disabled)
  CKT_2120_12131: MC nodes=316 CYME nodes=258, VA mean MC=0.99681 CYME=0.97777
Processing CKT_3882_09854...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_3882_09854.sxst
Load flow complete (all active controls disabled)
  CKT_3882_09854: MC nodes=542 CYME nodes=401, VA mean MC=0.92381 CYME=1.01619
Processing CKT_2315_04795...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_2315_04795.sxst
Load flow complete (all active controls disabled)
  CKT_2315_04795: MC nodes=482 CYME nodes=468, VA mean MC=0.99736 CYME=1.00318
Processing CKT_445_03850...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_445_03850.sxst
Load flow complete (all active controls disabled)
  CKT_445_03850: MC nodes=561 CYME nodes=561, VA mean MC=0.99585 CYME=1.00391
Processing CKT_2163_12395...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_2163_12395.sxst
Load flow complete (all active controls disabled)
  CKT_2163_12395: MC nodes=855 CYME nodes=787, VA mean MC=0.98167 CYME=1.01136
Processing CKT_2305_02600...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_2305_02600.sxst
Load flow complete (all active controls disabled)
  CKT_2305_02600: MC nodes=88 CYME nodes=88, VA mean MC=1.00756 CYME=1.00356
Processing CKT_3176_07820...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_3176_07820.sxst
Load flow complete (all active controls disabled)
  CKT_3176_07820: MC nodes=884 CYME nodes=879, VA mean MC=1.01411 CYME=1.00909
Processing CKT_2961_05200...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_2961_05200.sxst
Load flow complete (all active controls disabled)
  CKT_2961_05200: MC nodes=1029 CYME nodes=1006, VA mean MC=0.96136 CYME=0.95614
Processing CKT_5898_12775...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_5898_12775.sxst
Load flow complete (all active controls disabled)
  CKT_5898_12775: MC nodes=715 CYME nodes=622, VA mean MC=0.94866 CYME=1.00460
Processing CKT_1114_15680...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1114_15680.sxst
Load flow complete (all active controls disabled)
  CKT_1114_15680: MC nodes=1093 CYME nodes=996, VA mean MC=1.43538 CYME=1.02210
Processing CKT_30_14584...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_30_14584.sxst
Load flow complete (all active controls disabled)
  CKT_30_14584: MC nodes=414 CYME nodes=379, VA mean MC=0.99350 CYME=1.01426
Processing CKT_8860_18163...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_8860_18163.sxst
Load flow complete (all active controls disabled)
  CKT_8860_18163: MC nodes=501 CYME nodes=492, VA mean MC=0.97319 CYME=0.97040
Processing CKT_8807_08315...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_8807_08315.sxst
Load flow complete (all active controls disabled)
  CKT_8807_08315: MC nodes=1474 CYME nodes=1417, VA mean MC=0.98147 CYME=1.00804
Processing CKT_5371_03885...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_5371_03885.sxst
Load flow complete (all active controls disabled)
  CKT_5371_03885: MC nodes=1475 CYME nodes=1259, VA mean MC=5.17892 CYME=1.03497
Processing CKT_2317_06108...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_2317_06108.sxst
Load flow complete (all active controls disabled)
  CKT_2317_06108: MC nodes=145 CYME nodes=145, VA mean MC=1.00335 CYME=1.01567
Processing CKT_2496_02840...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_2496_02840.sxst
Load flow complete (all active controls disabled)
  CKT_2496_02840: MC nodes=599 CYME nodes=525, VA mean MC=0.95719 CYME=1.01131
Processing CKT_567_17405...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_567_17405.sxst
Load flow complete (all active controls disabled)
  CKT_567_17405: MC nodes=488 CYME nodes=471, VA mean MC=0.99995 CYME=1.00291
Processing CKT_3209_06888...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_3209_06888.sxst
Load flow complete (all active controls disabled)
  CKT_3209_06888: MC nodes=855 CYME nodes=828, VA mean MC=1.11498 CYME=0.83666
Processing CKT_381_14547...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_381_14547.sxst
Load flow complete (all active controls disabled)
  CKT_381_14547: MC nodes=1264 CYME nodes=1068, VA mean MC=1.20929 CYME=0.97583
Processing CKT_9208_09357...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_9208_09357.sxst
Load flow complete (all active controls disabled)
  CKT_9208_09357: MC nodes=626 CYME nodes=595, VA mean MC=0.98791 CYME=1.00467
Processing CKT_1833_19537...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_1833_19537.sxst
Load flow complete (all active controls disabled)
  CKT_1833_19537: MC nodes=1082 CYME nodes=958, VA mean MC=0.97519 CYME=0.78007
Processing CKT_5066_14189...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_5066_14189.sxst
Load flow complete (all active controls disabled)
  CKT_5066_14189: MC nodes=651 CYME nodes=633, VA mean MC=0.99913 CYME=1.00551
Processing CKT_3352_08271...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_3352_08271.sxst
Load flow complete (all active controls disabled)
  CKT_3352_08271: MC nodes=211 CYME nodes=210, VA mean MC=1.00323 CYME=1.03096
Processing CKT_3466_02876...
Opening:  c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\cyme\CKT_3466_02876.sxst
Load flow complete (all active controls disabled)
  CKT_3466_02876: MC nodes=522 CYME nodes=500, VA mean MC=1.00151 CYME=1.00212
Processing CKT_1964_01053...

,VA_MC_mean,VB_MC_mean,VC_MC_mean,MC_node_count,VA_CYME_mean,VB_CYME_mean,VC_CYME_mean,CYME_node_count,CKT_KEY
0,0.949925,0.949001,0.990828,719,1.005505,1.005505,1.005505,619,CKT_2155_12331
1,1.011674,1.090606,1.010080,1399,1.011734,1.011734,1.011734,998,CKT_3250_02485
2,0.989875,0.977278,0.989813,479,1.003064,1.003064,1.003064,473,CKT_156_06131
3,0.967460,0.965021,0.972518,829,0.963803,0.963803,0.963803,782,CKT_209_14375
4,1.090048,1.072761,1.292763,763,1.004819,1.004819,1.004819,699,CKT_1727_14043
...,...,...,...,...,...,...,...,...,...
833,0.999293,0.999293,0.999292,391,1.010518,1.010518,1.010518,391,CKT_2082_11931
834,0.980956,0.980368,0.982717,1706,1.010950,1.010950,1.010950,1699,CKT_4892_11166
835,0.980839,0.978022,0.979799,1045,1.005887,1.005887,1.005887,978,CKT_1909_00720
836,0.942852,0.933449,0.944933,759,1.004700,1.004700,1.004700,625,CKT_3458_11675
837,1.014614,1.022829,1.015441,275,1.011109,1.011109,1.011109,275,CKT_356_11512

In [15]:
import os, ctypes

# Pre-load KLUSolve.dll from py_dss_interface to avoid picking up CYME's copy
try:
    import py_dss_interface as _pdi
    _pdi_dll_dir = os.path.join(
        os.path.dirname(_pdi.__file__),
        'opendss_official', 'windows', 'delphi', 'x64',
    )
    _klu_path = os.path.join(_pdi_dll_dir, 'KLUSolve.dll')
    if os.path.isfile(_klu_path):
        if hasattr(os, 'add_dll_directory'):
            os.add_dll_directory(_pdi_dll_dir)
        ctypes.WinDLL(_klu_path)
except Exception:
    pass

from opendss.pf.powerflow import run_pf as dss_run_pf


def run_dss(dss_file):
    """Run OpenDSS power flow and return the result dict (keeps DSS session alive)."""
    result = dss_run_pf(dss_file)
    if not result['converged']:
        print(f"  WARNING: DSS did not converge for {dss_file}")
    else:
        print("DSS power flow converged")
    return result


def _get_dss_v_pu(dss_result):
    """Extract per-bus VA, VB, VC (pu) from an OpenDSS result dict."""
    d = dss_result['dss']
    rows = []
    for i in range(d.circuit.num_buses):
        d.circuit.set_active_bus_i(i)
        name = d.bus.name
        nodes = list(d.bus.nodes)          # e.g. [1, 2, 3]
        va_pu = d.bus.vmag_angle_pu        # [mag1, ang1, mag2, ang2, ...]

        v = {'NODE_ID': name, 'VA_DSS': None, 'VB_DSS': None, 'VC_DSS': None}
        phase_col = {1: 'VA_DSS', 2: 'VB_DSS', 3: 'VC_DSS'}
        for j, node in enumerate(nodes):
            if node in phase_col and j * 2 < len(va_pu):
                v[phase_col[node]] = va_pu[j * 2]
        rows.append(v)
    return pd.DataFrame(rows)


def compare_mc_dss(net, dss_file):
    """Run MC and OpenDSS, compute network-wide mean v_pu independently."""
    from multiconductor.pycci.cci_powerflow import run_pf

    # OpenDSS
    dss_result = run_dss(dss_file)
    df_dss = _get_dss_v_pu(dss_result)
    for c in ['VA_DSS', 'VB_DSS', 'VC_DSS']:
        df_dss[c] = pd.to_numeric(df_dss[c], errors='coerce')
    df_dss = df_dss.dropna(subset=['VA_DSS', 'VB_DSS', 'VC_DSS'])

    # MC
    run_pf(net, tol_vang_rad=1e-5, tol_vmag_pu=1e-5)
    df_mc = _get_mc_v_pu(net)
    for c in ['VA_MC', 'VB_MC', 'VC_MC']:
        df_mc[c] = pd.to_numeric(df_mc[c], errors='coerce')
    df_mc = df_mc.dropna(subset=['VA_MC', 'VB_MC', 'VC_MC'])

    summary = {
        'VA_MC_mean':   df_mc['VA_MC'].mean(),
        'VB_MC_mean':   df_mc['VB_MC'].mean(),
        'VC_MC_mean':   df_mc['VC_MC'].mean(),
        'MC_node_count': len(df_mc),
        'VA_DSS_mean':  df_dss['VA_DSS'].mean(),
        'VB_DSS_mean':  df_dss['VB_DSS'].mean(),
        'VC_DSS_mean':  df_dss['VC_DSS'].mean(),
        'DSS_node_count': len(df_dss),
    }
    return summary

In [16]:
def run_circuit2(circuit_key):
    import pickle
    from pathlib import Path

    print(f"Processing {circuit_key}...")
    pkl_file = Path(rf"c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\{circuit_key}.pkl")
    dss_file = Path(rf"c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\{circuit_key}.dss")

    with open(pkl_file, 'rb') as fh:
        net = pickle.load(fh)

    summary = compare_mc_dss(net, str(dss_file))

    summary['CKT_KEY'] = circuit_key
    print(f"  {circuit_key}: MC nodes={summary['MC_node_count']} DSS nodes={summary['DSS_node_count']}, "
          f"VA mean MC={summary['VA_MC_mean']:.5f} DSS={summary['VA_DSS_mean']:.5f}")
    return summary

In [17]:
all_summaries2 = []
for circuit_key in df['CIRCUIT_KEY']:
    try:
        summary = run_circuit2(circuit_key)
        all_summaries2.append(summary)
    except Exception as e:
        print(f"Error running circuit {circuit_key}: {e}")

summary2_df = pd.DataFrame(all_summaries2)
summary2_df

Processing CKT_2155_12331...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_2155_12331.dss
  CKT_2155_12331: MC nodes=719 DSS nodes=1065, VA mean MC=0.94993 DSS=0.85242
Processing CKT_3250_02485...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_3250_02485.dss
  CKT_3250_02485: MC nodes=1399 DSS nodes=2219, VA mean MC=1.01167 DSS=0.81925
Processing CKT_156_06131...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_156_06131.dss
  CKT_156_06131: MC nodes=479 DSS nodes=497, VA mean MC=0.98987 DSS=0.96438
Processing CKT_209_14375...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_209_14375.dss
  CKT_209_14375: MC nodes=829 DSS nodes=898, VA mean MC=0.96746 DSS=0.93520
Processing CKT_1727_14043...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_1727_14043.dss
  CKT_1727_14043: MC nodes=763 DSS nodes=944, VA mean MC=1.09005 DSS=0.93266
Processing CKT_1747_14145...
DSS power flow converged
  CKT_1747_14145: MC nodes=2 DSS nodes=217, VA mean MC=1.00000 DSS=0.00922
Processing CKT_4372_05219...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_4372_05219.dss
  CKT_4372_05219: MC nodes=510 DSS nodes=591, VA mean MC=1.00104 DSS=0.89907
Processing CKT_1051_12960...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_1051_12960.dss
  CKT_1051_12960: MC nodes=1260 DSS nodes=1536, VA mean MC=0.99906 DSS=0.96227
Processing CKT_3953_09972...
DSS power flow converged
  CKT_3953_09972: MC nodes=407 DSS nodes=433, VA mean MC=0.99277 DSS=0.96832
Processing CKT_4337_10933...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_4337_10933.dss
  CKT_4337_10933: MC nodes=358 DSS nodes=378, VA mean MC=0.99647 DSS=0.94465
Processing CKT_4186_02037...
DSS power flow converged
  CKT_4186_02037: MC nodes=248 DSS nodes=258, VA mean MC=0.99696 DSS=0.95832
Processing CKT_2751_02720...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_2751_02720.dss
  CKT_2751_02720: MC nodes=1005 DSS nodes=1541, VA mean MC=0.93762 DSS=0.84486
Processing CKT_247_16926...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_247_16926.dss
  CKT_247_16926: MC nodes=259 DSS nodes=303, VA mean MC=1.00727 DSS=0.87937
Processing CKT_4365_16974...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_4365_16974.dss
  CKT_4365_16974: MC nodes=777 DSS nodes=805, VA mean MC=0.98978 DSS=0.95912
Processing CKT_4868_03943...
DSS power flow converged
  CKT_4868_03943: MC nodes=194 DSS nodes=206, VA mean MC=0.99794 DSS=0.93983
Processing CKT_9005_13663...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_9005_13663.dss
  CKT_9005_13663: MC nodes=725 DSS nodes=739, VA mean MC=0.99888 DSS=0.98502
Processing CKT_4338_05488...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_4338_05488.dss
  CKT_4338_05488: MC nodes=223 DSS nodes=227, VA mean MC=1.00030 DSS=0.98268
Processing CKT_4330_12571...
DSS power flow converged
  CKT_4330_12571: MC nodes=691 DSS nodes=1350, VA mean MC=0.91968 DSS=0.76590
Processing CKT_3024_07660...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_3024_07660.dss
  CKT_3024_07660: MC nodes=1419 DSS nodes=1692, VA mean MC=0.95464 DSS=0.90256
Processing CKT_361_15376...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_361_15376.dss
  CKT_361_15376: MC nodes=325 DSS nodes=365, VA mean MC=1.00507 DSS=0.89767
Processing CKT_2465_10435...
DSS power flow converged
  CKT_2465_10435: MC nodes=300 DSS nodes=308, VA mean MC=0.99727 DSS=0.97139
Processing CKT_3986_04130...
DSS power flow converged
  CKT_3986_04130: MC nodes=617 DSS nodes=779, VA mean MC=0.93888 DSS=0.86856
Processing CKT_5254_06448...
DSS power flow converged
  CKT_5254_06448: MC nodes=417 DSS nodes=425, VA mean MC=1.01230 DSS=0.99327
Processing CKT_2574_07870...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_2574_07870.dss
  CKT_2574_07870: MC nodes=810 DSS nodes=840, VA mean MC=0.96675 DSS=0.96142
Processing CKT_3265_05123...
DSS power flow converged
  CKT_3265_05123: MC nodes=45 DSS nodes=47, VA mean MC=0.99061 DSS=0.94845
Processing CKT_1043_18094...
DSS power flow converged
  CKT_1043_18094: MC nodes=177 DSS nodes=183, VA mean MC=0.99761 DSS=0.96490
Processing CKT_3796_06549...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_3796_06549.dss
  CKT_3796_06549: MC nodes=1328 DSS nodes=2061, VA mean MC=1.58914 DSS=0.83600
Processing CKT_2839_03328...
DSS power flow converged
  CKT_2839_03328: MC nodes=1759 DSS nodes=1980, VA mean MC=0.94639 DSS=0.90424
Processing CKT_6074_00727...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_6074_00727.dss
  CKT_6074_00727: MC nodes=864 DSS nodes=968, VA mean MC=0.99663 DSS=0.94970
Processing CKT_2403_05307...
DSS power flow converged
  CKT_2403_05307: MC nodes=721 DSS nodes=765, VA mean MC=0.97588 DSS=0.95491
Processing CKT_1393_13655...
DSS power flow converged
  CKT_1393_13655: MC nodes=60 DSS nodes=66, VA mean MC=1.00000 DSS=0.93939
Processing CKT_237_16860...
Error running circuit CKT_237_16860: [Errno 2] No such file or directory: 'c:\\Users\\fgonzales\\git\\mc-0.0.1.15\\networks_final\\CKT_237_16860.pkl'
Processing CKT_911_17870...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_911_17870.dss
  CKT_911_17870: MC nodes=1353 DSS nodes=1440, VA mean MC=0.98721 DSS=0.96448
Processing CKT_2443_03688...
DSS power flow converged
  CKT_2443_03688: MC nodes=678 DSS nodes=1136, VA mean MC=0.88857 DSS=0.72968
Processing CKT_1962_01050...
DSS power flow converged
  CKT_1962_01050: MC nodes=423 DSS nodes=429, VA mean MC=0.99177 DSS=0.97733
Processing CKT_3401_02768...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_3401_02768.dss
  CKT_3401_02768: MC nodes=418 DSS nodes=635, VA mean MC=0.93337 DSS=0.84060
Processing CKT_1883_00600...
Error running circuit CKT_1883_00600: [Errno 2] No such file or directory: 'c:\\Users\\fgonzales\\git\\mc-0.0.1.15\\networks_final\\CKT_1883_00600.pkl'
Processing CKT_1581_18950...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_1581_18950.dss
  CKT_1581_18950: MC nodes=562 DSS nodes=620, VA mean MC=0.99382 DSS=0.90396
Processing CKT_5777_03296...
Error running circuit CKT_5777_03296: [Errno 2] No such file or directory: 'c:\\Users\\fgonzales\\git\\mc-0.0.1.15\\networks_final\\CKT_5777_03296.pkl'
Processing CKT_3675_06230...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_3675_06230.dss
  CKT_3675_06230: MC nodes=516 DSS nodes=592, VA mean MC=0.97585 DSS=0.96647
Processing CKT_3080_07928...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_3080_07928.dss
  CKT_3080_07928: MC nodes=906 DSS nodes=1201, VA mean MC=0.97563 DSS=0.89472
Processing CKT_2404_07490...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_2404_07490.dss
  CKT_2404_07490: MC nodes=1232 DSS nodes=1452, VA mean MC=0.97113 DSS=0.91644
Processing CKT_1896_00669...
DSS power flow converged
  CKT_1896_00669: MC nodes=1062 DSS nodes=1236, VA mean MC=0.95774 DSS=0.90890
Processing CKT_1893_00663...
Error running circuit CKT_1893_00663: [Errno 2] No such file or directory: 'c:\\Users\\fgonzales\\git\\mc-0.0.1.15\\networks_final\\CKT_1893_00663.pkl'
Processing CKT_1547_16352...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_1547_16352.dss
  CKT_1547_16352: MC nodes=369 DSS nodes=511, VA mean MC=0.98688 DSS=0.92447
Processing CKT_1824_19417...
DSS power flow converged
  CKT_1824_19417: MC nodes=738 DSS nodes=859, VA mean MC=0.96334 DSS=0.93466
Processing CKT_2500_08194...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_2500_08194.dss
  CKT_2500_08194: MC nodes=804 DSS nodes=880, VA mean MC=0.98284 DSS=0.95660
Processing CKT_4854_12781...
DSS power flow converged
  CKT_4854_12781: MC nodes=671 DSS nodes=853, VA mean MC=0.96636 DSS=0.89209
Processing CKT_3058_03460...
DSS power flow converged
  CKT_3058_03460: MC nodes=777 DSS nodes=866, VA mean MC=0.97707 DSS=0.93969
Processing CKT_5902_19838...
DSS power flow converged
  CKT_5902_19838: MC nodes=323 DSS nodes=327, VA mean MC=0.99375 DSS=0.98162
Processing CKT_4800_10687...
DSS power flow converged
  CKT_4800_10687: MC nodes=225 DSS nodes=246, VA mean MC=0.99819 DSS=0.93334
Processing CKT_1419_16122...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_1419_16122.dss
  CKT_1419_16122: MC nodes=125 DSS nodes=169, VA mean MC=1.06070 DSS=0.96817
Processing CKT_2053_00870...
DSS power flow converged
  CKT_2053_00870: MC nodes=672 DSS nodes=746, VA mean MC=0.99501 DSS=0.92752
Processing CKT_3092_06357...
DSS power flow converged
  CKT_3092_06357: MC nodes=821 DSS nodes=995, VA mean MC=1.25701 DSS=0.93657
Processing CKT_435_17253...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_435_17253.dss
  CKT_435_17253: MC nodes=594 DSS nodes=731, VA mean MC=1.29777 DSS=0.81791
Processing CKT_2543_03584...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_2543_03584.dss
  CKT_2543_03584: MC nodes=1007 DSS nodes=1027, VA mean MC=8.73175 DSS=8.17591
Processing CKT_2947_06280...
DSS power flow converged
  CKT_2947_06280: MC nodes=462 DSS nodes=485, VA mean MC=1.00345 DSS=0.98701
Processing CKT_4176_01945...
DSS power flow converged
  CKT_4176_01945: MC nodes=65 DSS nodes=75, VA mean MC=0.99350 DSS=0.86103
Processing CKT_2120_12131...
DSS power flow converged
  CKT_2120_12131: MC nodes=316 DSS nodes=345, VA mean MC=0.99681 DSS=0.87606
Processing CKT_3882_09854...
DSS power flow converged
  CKT_3882_09854: MC nodes=542 DSS nodes=742, VA mean MC=0.92381 DSS=0.80764
Processing CKT_2315_04795...
DSS power flow converged
  CKT_2315_04795: MC nodes=482 DSS nodes=593, VA mean MC=0.99736 DSS=0.89680
Processing CKT_445_03850...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_445_03850.dss
  CKT_445_03850: MC nodes=561 DSS nodes=601, VA mean MC=0.99585 DSS=0.95347
Processing CKT_2163_12395...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_2163_12395.dss
  CKT_2163_12395: MC nodes=855 DSS nodes=983, VA mean MC=0.98167 DSS=0.93911
Processing CKT_2305_02600...
DSS power flow converged
  CKT_2305_02600: MC nodes=88 DSS nodes=96, VA mean MC=1.00756 DSS=0.92361
Processing CKT_3176_07820...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_3176_07820.dss
  CKT_3176_07820: MC nodes=884 DSS nodes=914, VA mean MC=1.01411 DSS=1.01028
Processing CKT_2961_05200...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_2961_05200.dss
  CKT_2961_05200: MC nodes=1029 DSS nodes=1094, VA mean MC=0.96136 DSS=0.93759
Processing CKT_5898_12775...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_5898_12775.dss
  CKT_5898_12775: MC nodes=715 DSS nodes=949, VA mean MC=0.94866 DSS=0.89476
Processing CKT_1114_15680...
DSS power flow converged
  CKT_1114_15680: MC nodes=1093 DSS nodes=1254, VA mean MC=1.43538 DSS=0.92486
Processing CKT_30_14584...
DSS power flow converged
  CKT_30_14584: MC nodes=414 DSS nodes=500, VA mean MC=0.99350 DSS=0.85593
Processing CKT_8860_18163...
DSS power flow converged
  CKT_8860_18163: MC nodes=501 DSS nodes=543, VA mean MC=0.97319 DSS=0.94027
Processing CKT_8807_08315...
DSS power flow converged
  CKT_8807_08315: MC nodes=1474 DSS nodes=1592, VA mean MC=0.98147 DSS=0.95613
Processing CKT_5371_03885...
DSS power flow converged
  CKT_5371_03885: MC nodes=1475 DSS nodes=2220, VA mean MC=5.17892 DSS=4.69477
Processing CKT_2317_06108...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_2317_06108.dss
  CKT_2317_06108: MC nodes=145 DSS nodes=168, VA mean MC=1.00335 DSS=0.89784
Processing CKT_2496_02840...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_2496_02840.dss
  CKT_2496_02840: MC nodes=599 DSS nodes=891, VA mean MC=0.95719 DSS=0.84780
Processing CKT_567_17405...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_567_17405.dss
  CKT_567_17405: MC nodes=488 DSS nodes=502, VA mean MC=0.99995 DSS=0.94925
Processing CKT_3209_06888...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_3209_06888.dss
  CKT_3209_06888: MC nodes=855 DSS nodes=920, VA mean MC=1.11498 DSS=0.94695
Processing CKT_381_14547...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_381_14547.dss
  CKT_381_14547: MC nodes=1264 DSS nodes=1427, VA mean MC=1.20929 DSS=0.90416
Processing CKT_9208_09357...
DSS power flow converged
  CKT_9208_09357: MC nodes=626 DSS nodes=714, VA mean MC=0.98791 DSS=0.91123
Processing CKT_1833_19537...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_1833_19537.dss
  CKT_1833_19537: MC nodes=1082 DSS nodes=1351, VA mean MC=0.97519 DSS=0.91793
Processing CKT_5066_14189...
DSS power flow converged
  CKT_5066_14189: MC nodes=651 DSS nodes=680, VA mean MC=0.99913 DSS=0.98164
Processing CKT_3352_08271...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_3352_08271.dss
  CKT_3352_08271: MC nodes=211 DSS nodes=222, VA mean MC=1.00323 DSS=0.96303
Processing CKT_3466_02876...
DSS power flow converged
  CKT_3466_02876: MC nodes=522 DSS nodes=563, VA mean MC=1.00151 DSS=0.95128
Processing CKT_1964_01053...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_1964_01053.dss
  CKT_1964_01053: MC nodes=1019 DSS nodes=1255, VA mean MC=0.96460 DSS=0.90331
Processing CKT_8_19693...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_8_19693.dss
  CKT_8_19693: MC nodes=411 DSS nodes=453, VA mean MC=0.99579 DSS=0.94006
Processing CKT_2994_08460...
Error running circuit CKT_2994_08460: [Errno 2] No such file or directory: 'c:\\Users\\fgonzales\\git\\mc-0.0.1.15\\networks_final\\CKT_2994_08460.pkl'
Processing CKT_2858_03000...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_2858_03000.dss
  CKT_2858_03000: MC nodes=1463 DSS nodes=1503, VA mean MC=0.98652 DSS=0.97866
Processing CKT_92_16775...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_92_16775.dss
  CKT_92_16775: MC nodes=682 DSS nodes=756, VA mean MC=0.97595 DSS=0.93705
Processing CKT_4884_08943...
DSS power flow converged
  CKT_4884_08943: MC nodes=452 DSS nodes=562, VA mean MC=1.00035 DSS=0.95291
Processing CKT_4870_06001...
DSS power flow converged
  CKT_4870_06001: MC nodes=720 DSS nodes=854, VA mean MC=1.33129 DSS=0.89994
Processing CKT_2063_11843...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_2063_11843.dss
  CKT_2063_11843: MC nodes=918 DSS nodes=936, VA mean MC=0.98888 DSS=0.97576
Processing CKT_2882_11364...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_2882_11364.dss
  CKT_2882_11364: MC nodes=1499 DSS nodes=1576, VA mean MC=0.98514 DSS=0.96163
Processing CKT_925_17912...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_925_17912.dss
  CKT_925_17912: MC nodes=249 DSS nodes=279, VA mean MC=1.00099 DSS=0.94460
Processing CKT_3368_08407...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_3368_08407.dss
  CKT_3368_08407: MC nodes=1053 DSS nodes=1263, VA mean MC=1.01971 DSS=0.93543
Processing CKT_414_17116...
DSS power flow converged
  CKT_414_17116: MC nodes=691 DSS nodes=745, VA mean MC=0.98247 DSS=0.94271
Processing CKT_4214_07661...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_4214_07661.dss
  CKT_4214_07661: MC nodes=307 DSS nodes=330, VA mean MC=1.00458 DSS=0.95395
Processing CKT_2282_09320...
DSS power flow converged
  CKT_2282_09320: MC nodes=1432 DSS nodes=2224, VA mean MC=2.28506 DSS=0.84762
Processing CKT_4753_01515...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_4753_01515.dss
  CKT_4753_01515: MC nodes=451 DSS nodes=563, VA mean MC=1.00516 DSS=0.98562
Processing CKT_3185_05707...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_3185_05707.dss
  CKT_3185_05707: MC nodes=829 DSS nodes=936, VA mean MC=0.96016 DSS=0.92541
Processing CKT_1161_13164...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_1161_13164.dss
  CKT_1161_13164: MC nodes=804 DSS nodes=1263, VA mean MC=0.95401 DSS=0.83932
Processing CKT_2200_12600...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_2200_12600.dss
  CKT_2200_12600: MC nodes=421 DSS nodes=477, VA mean MC=0.96498 DSS=0.91191
Processing CKT_5322_13201...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_5322_13201.dss
  CKT_5322_13201: MC nodes=1656 DSS nodes=1761, VA mean MC=0.96625 DSS=0.93738
Processing CKT_14460_19586...
DSS power flow converged
  CKT_14460_19586: MC nodes=911 DSS nodes=1324, VA mean MC=1.17682 DSS=0.84774
Processing CKT_4343_00813...
DSS power flow converged
  CKT_4343_00813: MC nodes=1338 DSS nodes=1504, VA mean MC=0.96623 DSS=0.90967
Processing CKT_3254_05068...
Error running circuit CKT_3254_05068: [Errno 2] No such file or directory: 'c:\\Users\\fgonzales\\git\\mc-0.0.1.15\\networks_final\\CKT_3254_05068.pkl'
Processing CKT_1376_13587...
Error running circuit CKT_1376_13587: [Errno 2] No such file or directory: 'c:\\Users\\fgonzales\\git\\mc-0.0.1.15\\networks_final\\CKT_1376_13587.pkl'
Processing CKT_4022_10102...
DSS power flow converged
  CKT_4022_10102: MC nodes=306 DSS nodes=312, VA mean MC=0.99586 DSS=0.97671
Processing CKT_1408_13737...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_1408_13737.dss
  CKT_1408_13737: MC nodes=519 DSS nodes=640, VA mean MC=1.01357 DSS=0.94781
Processing CKT_3376_11362...
DSS power flow converged
  CKT_3376_11362: MC nodes=732 DSS nodes=1428, VA mean MC=0.98996 DSS=0.84603
Processing CKT_450_05079...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_450_05079.dss
  CKT_450_05079: MC nodes=211 DSS nodes=236, VA mean MC=1.00238 DSS=0.91885
Processing CKT_4824_09811...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_4824_09811.dss
  CKT_4824_09811: MC nodes=285 DSS nodes=315, VA mean MC=0.99907 DSS=0.96325
Processing CKT_3588_08938...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_3588_08938.dss
  CKT_3588_08938: MC nodes=172 DSS nodes=190, VA mean MC=0.98837 DSS=0.92664
Processing CKT_472_16666...
  WARNING: DSS did not converge for c:\Users\fgonzales\git\mc-0.0.1.15\networks_final\dss\CKT_472_16666.dss

,VA_MC_mean,VB_MC_mean,VC_MC_mean,MC_node_count,VA_DSS_mean,VB_DSS_mean,VC_DSS_mean,DSS_node_count,CKT_KEY
0,0.949925,0.949001,0.990828,719,0.852418,0.855191,0.852251,1065,CKT_2155_12331
1,1.011674,1.090606,1.010080,1399,0.819246,0.818204,0.825515,2219,CKT_3250_02485
2,0.989875,0.977278,0.989813,479,0.964375,0.942441,0.964331,497,CKT_156_06131
3,0.967460,0.965021,0.972518,829,0.935202,0.935149,0.930923,898,CKT_209_14375
4,1.090048,1.072761,1.292763,763,0.932661,0.865583,0.838813,944,CKT_1727_14043
...,...,...,...,...,...,...,...,...,...
877,0.999293,0.999293,0.999292,391,0.989198,0.989197,0.989197,395,CKT_2082_11931
878,0.980956,0.980368,0.982717,1706,0.967987,0.964084,0.965268,1746,CKT_4892_11166
879,0.980839,0.978022,0.979799,1045,0.937624,0.927718,0.924618,1209,CKT_1909_00720
880,0.942852,0.933449,0.944933,759,0.852389,0.850458,0.872438,1067,CKT_3458_11675
881,1.014614,1.022829,1.015441,275,0.971515,0.982814,0.914482,306,CKT_356_11512