## MC vs CYME: Bus Voltage & Transformer Configuration Comparison

#### Compare assigned bus voltages (`vn_kv`) and transformer configurations between the multiconductor
##### net objects and what CYME actually uses after the mc→CYME conversion.

### **Key differences to check:**
##### 1. **Bus base voltages** — MC stores explicit `vn_kv` per bus; CYME sets `UserDefinedBaseVoltage` only on transformer LV nodes
##### 2. **Transformer winding voltages** — MC converts L-L → winding voltage (÷√3 for Y, direct for D); CYME uses L-L directly
##### 3. **Connection type** — MC stores full vector group (from_phase/to_phase per circuit); CYME simplifies to `D_Yg` / `Yg_Yg`
##### 4. **Impedance split** — MC stores half-impedance per winding side; CYME uses total positive-sequence %Z
##### 5. **Power flow settings** — CYME disables line charging and voltage-sensitive loads by default -->

In [2]:
import pickle, math, os, time
from pathlib import Path
import pandas as pd
import numpy as np

PHASE_INT_TO_LETTER = {0: 'N', 1: 'A', 2: 'B', 3: 'C'}


def compare_bus_voltages_and_transformers(net, circuit_name):
    """Extract bus voltages and transformer configs from an mc net object
    and compute the equivalent CYME representation side-by-side."""

    # ------------------------------------------------------------------ #
    # PRE-COMPUTE LOOKUPS (avoid repeated DataFrame operations)          #
    # ------------------------------------------------------------------ #

    # -- Source bus lookup --
    source_buses = {}  # {bus_idx: vm_pu}
    for eg_name in ["ext_grid_sequence", "ext_grid"]:
        if eg_name in net and not net[eg_name].empty:
            eg = net[eg_name]
            if "bus" in eg.columns:
                for bus_idx in eg["bus"].unique():
                    mask = eg["bus"] == bus_idx
                    source_buses[int(bus_idx)] = float(eg.loc[mask, "vm_pu"].iloc[0])
            elif "bus" in eg.index.names:
                level = eg.index.names.index("bus")
                for bus_idx in eg.index.get_level_values(level).unique():
                    source_buses[int(bus_idx)] = 1.0

    # -- Transformer LV bus lookup (built once, not per-bus) --
    trafo_lv_map = {}  # {lv_bus_idx: trafo_name}
    trafo_flat_cache = {}  # {trafo_idx: (flat_df, buses, ordered_df)}
    if "trafo1ph" in net and not net["trafo1ph"].empty:
        trafo_indices = net.trafo1ph.index.get_level_values(0).unique()
        for t_idx in trafo_indices:
            t_data = net.trafo1ph.loc[t_idx]
            if isinstance(t_data, pd.Series):
                t_data = t_data.to_frame().T
            ordered_df = t_data.copy()
            flat = t_data.reset_index() if isinstance(t_data.index, pd.MultiIndex) else t_data

            if "bus" in flat.columns:
                bus_values = pd.to_numeric(flat["bus"], errors="coerce").dropna().astype(int).tolist()
                buses = sorted(set(bus_values))
            else:
                buses = sorted(set(flat.index.get_level_values("bus")))

            trafo_flat_cache[t_idx] = (flat, buses, ordered_df)
            if len(buses) >= 2:
                trafo_lv_map[buses[1]] = f"trafo_{t_idx}"

    # -- Bus name/vn_kv lookup (vectorized) --
    bus_indices = net.bus.index.get_level_values(0).unique()

    # ------------------------------------------------------------------ #
    # 1. BUS VOLTAGE TABLE                                                #
    # ------------------------------------------------------------------ #
    bus_rows = []
    for bus_idx in bus_indices:
        bus_data = net.bus.loc[bus_idx]
        if isinstance(bus_data, pd.DataFrame):
            name = bus_data["name"].iloc[0]
            vn_kv = float(bus_data["vn_kv"].iloc[0])
            phases = sorted(set(bus_data.index.get_level_values(-1)) - {0})
        else:
            name = bus_data["name"]
            vn_kv = float(bus_data["vn_kv"])
            phases = []

        phase_str = "".join(PHASE_INT_TO_LETTER.get(p, "") for p in phases)
        is_source = bus_idx in source_buses
        vm_pu = source_buses.get(bus_idx, 1.0)
        is_trafo_lv = bus_idx in trafo_lv_map
        trafo_name = trafo_lv_map.get(bus_idx, "")

        cyme_base_voltage = vn_kv if (is_trafo_lv or is_source) else "inherited/unset"
        cyme_operating_kv = round(vn_kv * vm_pu / math.sqrt(3), 6) if is_source else ""

        bus_rows.append(
            {
                "CKT_KEY": circuit_name,
                "BUS_IDX": bus_idx,
                "BUS_NAME": name,
                "PHASES": phase_str,
                "MC_VN_KV (L-L)": vn_kv,
                "IS_SOURCE": is_source,
                "IS_TRAFO_LV": is_trafo_lv,
                "TRAFO_NAME": trafo_name,
                "CYME_UserDefinedBaseVoltage": cyme_base_voltage,
                "CYME_OperatingVoltage_LN": cyme_operating_kv,
                "VM_PU": vm_pu if is_source else "",
            }
        )

    df_buses = pd.DataFrame(bus_rows)

    def _split_hv_lv_rows(flat_df, ordered_df, hv_bus_idx, lv_bus_idx):
        """Return HV-side and LV-side row DataFrames.

        Preferred path uses bus ownership per row. Fallback uses MC ordering:
        first half rows are HV side, second half are LV side.
        """
        hv_side = pd.DataFrame(columns=flat_df.columns)
        lv_side = pd.DataFrame(columns=flat_df.columns)

        if "bus" in flat_df.columns:
            bus_num = pd.to_numeric(flat_df["bus"], errors="coerce")
            hv_side = flat_df.loc[bus_num == int(hv_bus_idx)]
            lv_side = flat_df.loc[bus_num == int(lv_bus_idx)]

        if hv_side.empty or lv_side.empty:
            n = len(ordered_df)
            if n:
                split = max(1, n // 2)
                hv_side = ordered_df.iloc[:split].copy()
                lv_side = ordered_df.iloc[split:].copy() if n > split else ordered_df.iloc[-split:].copy()
                hv_side = hv_side.reset_index(drop=True)
                lv_side = lv_side.reset_index(drop=True)

        return hv_side, lv_side

    def _side_connection_from_phases(side_df):
        """Derive winding type from phase wiring only.

        Rule: to_phase == 0 -> Wye, to_phase != 0 -> Delta.
        """
        if side_df.empty or "to_phase" not in side_df.columns:
            return "?"

        to_vals = pd.to_numeric(side_df["to_phase"], errors="coerce").dropna().astype(int)
        if to_vals.empty:
            return "?"

        if (to_vals == 0).all():
            return "Y"
        if (to_vals != 0).all():
            return "D"
        return "?"

    def _mean_vn_kv(side_df):
        if side_df.empty or "vn_kv" not in side_df.columns:
            return 0.0
        vals = pd.to_numeric(side_df["vn_kv"], errors="coerce").dropna().astype(float)
        return float(vals.mean()) if not vals.empty else 0.0

    def _phases_to_letters(values):
        out = []
        for p in values:
            try:
                out.append(PHASE_INT_TO_LETTER.get(int(p), "?"))
            except Exception:
                out.append("?")
        return out

    # ------------------------------------------------------------------ #
    # 2. TRANSFORMER TABLE (uses cached flat DataFrames)                 #
    # ------------------------------------------------------------------ #
    trafo_rows = []
    tol_kv = 0.01

    for t_idx, (flat, buses, ordered_t_data) in trafo_flat_cache.items():
        hv_bus = buses[0]
        lv_bus = buses[1] if len(buses) > 1 else buses[0]

        first = flat.iloc[0]
        sn_mva = float(first.get("sn_mva", 0))
        vk_pct = float(first.get("vk_percent", 0))
        vkr_pct = float(first.get("vkr_percent", 0))
        tap_pos = float(first.get("tap_pos", 0))

        hv_vn_kv = (
            float(net.bus.loc[(hv_bus, 1)]["vn_kv"])
            if (hv_bus, 1) in net.bus.index
            else float(net.bus.loc[hv_bus].iloc[0]["vn_kv"])
        )
        lv_vn_kv = (
            float(net.bus.loc[(lv_bus, 1)]["vn_kv"])
            if (lv_bus, 1) in net.bus.index
            else float(net.bus.loc[lv_bus].iloc[0]["vn_kv"])
        )

        hv_side, lv_side = _split_hv_lv_rows(flat, ordered_t_data, hv_bus, lv_bus)

        hv_conn_type = _side_connection_from_phases(hv_side)
        lv_conn_type = _side_connection_from_phases(lv_side)
        mc_connection = f"{hv_conn_type}_{lv_conn_type}"

        hv_winding = _mean_vn_kv(hv_side)
        lv_winding = _mean_vn_kv(lv_side)

        # Secondary voltage calculated from winding connection + winding voltage.
        if lv_conn_type == "Y":
            calculated_secondary_ll_kv = lv_winding * math.sqrt(3)
        elif lv_conn_type == "D":
            calculated_secondary_ll_kv = lv_winding
        else:
            calculated_secondary_ll_kv = np.nan

        cyme_secondary_ll_kv = lv_vn_kv

        calc_vs_bus_match = (
            abs(calculated_secondary_ll_kv - lv_vn_kv) <= tol_kv
            if pd.notna(calculated_secondary_ll_kv)
            else False
        )
        calc_vs_cyme_match = (
            abs(calculated_secondary_ll_kv - cyme_secondary_ll_kv) <= tol_kv
            if pd.notna(calculated_secondary_ll_kv)
            else False
        )
        secondary_voltage_all_match = calc_vs_bus_match and calc_vs_cyme_match

        # Keep old all-row views for compatibility with existing notebook outputs.
        from_phases = flat["from_phase"].values.tolist() if "from_phase" in flat.columns else []
        to_phases = flat["to_phase"].values.tolist() if "to_phase" in flat.columns else []

        tp_set = set(int(x) for x in pd.to_numeric(pd.Series(to_phases), errors="coerce").dropna().astype(int).tolist()) if to_phases else set()
        has_delta = any(tp != 0 for tp in tp_set)
        cyme_connection = "D_Yg" if has_delta else "Yg_Yg"

        cyme_z1_pct = vk_pct
        cyme_x1r1 = round(math.sqrt(max(0, (vk_pct / vkr_pct) ** 2 - 1)), 4) if vkr_pct > 0 else 10.0
        cyme_rating_kva = sn_mva * 1000
        mc_total_sn_mva = sn_mva * len(flat) / len(buses)

        trafo_rows.append(
            {
                "CKT_KEY": circuit_name,
                "TRAFO_IDX": t_idx,
                "HV_BUS": hv_bus,
                "LV_BUS": lv_bus,
                "HV_BUS_VN_KV": hv_vn_kv,
                "LV_BUS_VN_KV": lv_vn_kv,
                "MC_HV_WINDING_KV": hv_winding,
                "MC_LV_WINDING_KV": lv_winding,
                "MC_CONNECTION (derived)": mc_connection,
                "CYME_CONNECTION": cyme_connection,
                "CONNECTION_MATCH": mc_connection.replace("_", "") == cyme_connection.replace("_", "").replace("g", ""),
                "MC_HV_FROM_PHASES": _phases_to_letters(hv_side["from_phase"].tolist()) if "from_phase" in hv_side.columns else [],
                "MC_HV_TO_PHASES": _phases_to_letters(hv_side["to_phase"].tolist()) if "to_phase" in hv_side.columns else [],
                "MC_LV_FROM_PHASES": _phases_to_letters(lv_side["from_phase"].tolist()) if "from_phase" in lv_side.columns else [],
                "MC_LV_TO_PHASES": _phases_to_letters(lv_side["to_phase"].tolist()) if "to_phase" in lv_side.columns else [],
                "MC_FROM_PHASES": _phases_to_letters(from_phases),
                "MC_TO_PHASES": _phases_to_letters(to_phases),
                "MC_SN_MVA_PER_CIRCUIT": sn_mva,
                "MC_TOTAL_SN_MVA": mc_total_sn_mva,
                "MC_VK_PCT (per side)": vk_pct,
                "MC_VKR_PCT (per side)": vkr_pct,
                "CYME_Z1_PCT (fed as-is from mc)": cyme_z1_pct,
                "CYME_X1R1_RATIO": cyme_x1r1,
                "CYME_PrimaryV (L-L)": hv_vn_kv,
                "CYME_SecondaryV (L-L)": cyme_secondary_ll_kv,
                "CALCULATED_SecondaryV (L-L)": calculated_secondary_ll_kv,
                "CALC_vs_BUS_MATCH": calc_vs_bus_match,
                "CALC_vs_CYME_MATCH": calc_vs_cyme_match,
                "SECONDARY_VOLTAGE_ALL_MATCH": secondary_voltage_all_match,
                "CYME_RatingKVA": cyme_rating_kva,
                "MC_TAP_POS": tap_pos,
                "N_CIRCUITS": len(flat),
            }
        )

    df_trafos = pd.DataFrame(trafo_rows)
    return df_buses, df_trafos


# --- Run for all validation circuits ---
pkl_dir = Path(r"c:\Users\fgonzales\git\mc-0.0.1.15\networks_final")
pkl_files = sorted(pkl_dir.glob("*.pkl"))
total_files = len(pkl_files)

bus_comparison_all = []
trafo_comparison_all = []

t_start = time.time()
for i, pkl_file in enumerate(pkl_files, 1):
    circuit_key = pkl_file.stem
    t0 = time.time()
    with open(pkl_file, "rb") as fh:
        net = pickle.load(fh)

    df_b, df_t = compare_bus_voltages_and_transformers(net, circuit_key)
    bus_comparison_all.append(df_b)
    trafo_comparison_all.append(df_t)

    elapsed = time.time() - t0
    total_elapsed = time.time() - t_start
    avg_per = total_elapsed / i
    eta = avg_per * (total_files - i)
    print(
        f"[{i}/{total_files}] {circuit_key}: {len(df_b)} buses, {len(df_t)} trafos  "
        f"({elapsed:.1f}s, ETA {eta:.0f}s)"
    )

df_all_buses = pd.concat(bus_comparison_all, ignore_index=True) if bus_comparison_all else pd.DataFrame()
df_all_trafos = pd.concat(trafo_comparison_all, ignore_index=True) if trafo_comparison_all else pd.DataFrame()

print(
    f"\nDone in {time.time() - t_start:.1f}s - "
    f"{len(df_all_buses)} bus entries, {len(df_all_trafos)} transformer entries across {len(bus_comparison_all)} circuits"
)

[1/882] CKT_100_16795: 2067 buses, 374 trafos  (1.8s, ETA 1565s)
[2/882] CKT_1014_17972: 3361 buses, 681 trafos  (2.6s, ETA 1915s)
[3/882] CKT_1019_17995: 1578 buses, 293 trafos  (1.1s, ETA 1609s)
[4/882] CKT_1021_18000: 1518 buses, 274 trafos  (1.0s, ETA 1419s)
[5/882] CKT_1025_18018: 1866 buses, 308 trafos  (1.1s, ETA 1328s)
[6/882] CKT_1029_18017: 1002 buses, 167 trafos  (0.6s, ETA 1198s)
[7/882] CKT_1031_18043: 523 buses, 17 trafos  (0.2s, ETA 1052s)
[8/882] CKT_1033_18045: 1705 buses, 304 trafos  (1.0s, ETA 1024s)
[9/882] CKT_1040_18076: 540 buses, 89 trafos  (0.4s, ETA 947s)
[10/882] CKT_1043_18094: 199 buses, 8 trafos  (0.1s, ETA 858s)
[11/882] CKT_1048_13343: 1503 buses, 279 trafos  (0.9s, ETA 851s)
[12/882] CKT_1051_12960: 2562 buses, 425 trafos  (1.6s, ETA 896s)
[13/882] CKT_1053_12976: 2203 buses, 332 trafos  (1.4s, ETA 923s)
[14/882] CKT_1074_13087: 193 buses, 10 trafos  (0.1s, ETA 862s)
[15/882] CKT_1093_15603: 1731 buses, 323 trafos  (1.4s, ETA 883s)
[16/882] CKT_1096_15608: 1121 buses, 137 trafos  (0.7s, ETA 864s)
[17/882] CKT_1105_15643: 1383 buses, 176 trafos  (0.7s, ETA 848s)
[18/882] CKT_1106_15646: 1887 buses, 356 trafos  (1.5s, ETA 870s)
[19/882] CKT_1108_15648: 1883 buses, 362 trafos  (1.4s, ETA 888s)
[20/882] CKT_1112_15670: 1805 buses, 312 trafos  (1.3s, ETA 897s)
[21/882] CKT_1114_15680: 1748 buses, 314 trafos  (1.3s, ETA 907s)
[22/882] CKT_1135_18140: 1674 buses, 315 trafos  (1.5s, ETA 922s)
[23/882] CKT_1146_18180: 1376 buses, 201 trafos  (0.9s, ETA 914s)
[24/882] CKT_114_16955: 454 buses, 73 trafos  (0.3s, ETA 887s)
[25/882] CKT_1152_18222: 789 buses, 119 trafos  (0.5s, ETA 867s)
[26/882] CKT_115_17030: 2598 buses, 492 trafos  (2.0s, ETA 897s)
[27/882] CKT_1161_13164: 2101 buses, 411 trafos  (1.6s, ETA 914s)
[28/882] CKT_1163_13178: 1626 buses, 281 trafos  (1.3s, ETA 919s)
[29/882] CKT_1173_13253: 3629 buses, 420 trafos  (1.9s, ETA 942s)
[30/882] CKT_1174_13256: 1085 buses, 212 trafos  (0.8s, ETA 932s)
[31/882] CKT_1181_13310: 1472 buses, 233 trafos  (1.0s, ETA 927s)
[32/882] CKT_1190_13355: 1217 buses, 160 trafos  (0.7s, ETA 915s)
[33/882] CKT_1200_15715: 2075 buses, 374 trafos  (1.5s, ETA 926s)
[34/882] CKT_1203_15737: 2328 buses, 326 trafos  (1.5s, ETA 936s)
[35/882] CKT_1209_15758: 1362 buses, 212 trafos  (0.9s, ETA 930s)
[36/882] CKT_1213_15865: 90 buses, 7 trafos  (0.1s, ETA 905s)
[37/882] CKT_1215_15880: 1165 buses, 206 trafos  (0.9s, ETA 900s)
[38/882] CKT_1221_15910: 217 buses, 29 trafos  (0.1s, ETA 878s)
[39/882] CKT_1224_15922: 2914 buses, 557 trafos  (2.1s, ETA 901s)
[40/882] CKT_1228_15953: 133 buses, 9 trafos  (0.1s, ETA 879s)
[41/882] CKT_1241_18271: 1329 buses, 233 trafos  (0.9s, ETA 876s)
[42/882] CKT_1245_18295: 833 buses, 110 trafos  (0.4s, ETA 863s)
[43/882] CKT_1247_18301: 721 buses, 106 trafos  (0.4s, ETA 850s)
[44/882] CKT_1248_18307: 1993 buses, 415 trafos  (1.6s, ETA 861s)
[45/882] CKT_1253_18330: 2415 buses, 450 trafos  (1.8s, ETA 875s)
[46/882] CKT_1255_18335: 4794 buses, 927 trafos  (3.6s, ETA 920s)
[47/882] CKT_1259_18370: 1621 buses, 266 trafos  (1.2s, ETA 920s)
[48/882] CKT_1269_13386: 445 buses, 22 trafos  (0.2s, ETA 903s)
[49/882] CKT_1277_13467: 1404 buses, 268 trafos  (0.9s, ETA 899s)
[50/882] CKT_1284_13508: 1888 buses, 230 trafos  (1.1s, ETA 898s)
[51/882] CKT_1289_13538: 945 buses, 152 trafos  (0.6s, ETA 890s)
[52/882] CKT_1295_13565: 1240 buses, 208 trafos  (0.9s, ETA 885s)
[53/882] CKT_1313_16007: 218 buses, 25 trafos  (0.1s, ETA 870s)
[54/882] CKT_1317_16013: 61 buses, 4 trafos  (0.1s, ETA 854s)
[55/882] CKT_1321_16030: 307 buses, 28 trafos  (0.2s, ETA 840s)
[56/882] CKT_1323_16043: 2731 buses, 551 trafos  (2.3s, ETA 858s)
[57/882] CKT_1326_16049: 1041 buses, 155 trafos  (0.9s, ETA 855s)
[58/882] CKT_1330_16073: 592 buses, 92 trafos  (0.4s, ETA 845s)
[59/882] CKT_133_19655: 730 buses, 120 trafos  (0.6s, ETA 838s)
[60/882] CKT_1348_18580: 371 buses, 42 trafos  (0.2s, ETA 826s)
[61/882] CKT_1352_18525: 3415 buses, 565 trafos  (2.2s, ETA 841s)
[62/882] CKT_1363_18610: 2381 buses, 434 trafos  (1.9s, ETA 852s)
[63/882] CKT_136_19670: 1405 buses, 252 trafos  (1.1s, ETA 851s)
[64/882] CKT_1372_18408: 2419 buses, 407 trafos  (1.6s, ETA 858s)
[65/882] CKT_1374_18629: 1730 buses, 310 trafos  (1.6s, ETA 864s)
[66/882] CKT_137_19697: 1550 buses, 221 trafos  (0.8s, ETA 860s)
[67/882] CKT_1381_13610: 105 buses, 12 trafos  (0.1s, ETA 848s)
[68/882] CKT_1393_13655: 71 buses, 3 trafos  (0.1s, ETA 835s)
[69/882] CKT_1396_13660: 1507 buses, 243 trafos  (1.1s, ETA 834s)
[70/882] CKT_1398_13680: 629 buses, 94 trafos  (0.4s, ETA 826s)
[71/882] CKT_1400_13695: 1317 buses, 189 trafos  (0.7s, ETA 822s)
[72/882] CKT_1404_13720: 758 buses, 111 trafos  (0.5s, ETA 815s)
[73/882] CKT_1408_13737: 2179 buses, 337 trafos  (1.4s, ETA 819s)
[74/882] CKT_140_19700: 236 buses, 29 trafos  (0.1s, ETA 808s)
[75/882] CKT_1419_16122: 246 buses, 43 trafos  (0.2s, ETA 799s)
[76/882] CKT_1427_16147: 985 buses, 112 trafos  (0.7s, ETA 794s)
[77/882] CKT_1429_13580: 1320 buses, 228 trafos  (0.9s, ETA 792s)
[78/882] CKT_1435_16200: 1602 buses, 252 trafos  (1.4s, ETA 796s)
[79/882] CKT_1437_16220: 2476 buses, 428 trafos  (1.8s, ETA 803s)
[80/882] CKT_1440_10580: 1127 buses, 182 trafos  (0.9s, ETA 801s)
[81/882] CKT_14428_06451: 600 buses, 36 trafos  (0.2s, ETA 792s)
[82/882] CKT_1444_16267: 850 buses, 154 trafos  (0.6s, ETA 787s)
[83/882] CKT_14450_09805: 1228 buses, 162 trafos  (0.6s, ETA 783s)
[84/882] CKT_14460_19586: 2481 buses, 441 trafos  (1.8s, ETA 790s)
[85/882] CKT_14486_03004: 2178 buses, 275 trafos  (1.4s, ETA 793s)
[86/882] CKT_14518_07417: 4859 buses, 880 trafos  (3.7s, ETA 817s)
[87/882] CKT_1458_18674: 212 buses, 11 trafos  (0.1s, ETA 807s)
[88/882] CKT_1459_18657: 1398 buses, 249 trafos  (0.9s, ETA 805s)
[89/882] CKT_14606_11476: 1722 buses, 315 trafos  (1.2s, ETA 806s)
[90/882] CKT_14611_06530: 1475 buses, 272 trafos  (1.2s, ETA 806s)
[91/882] CKT_14623_16124: 37 buses, 1 trafos  (0.1s, ETA 797s)
[92/882] CKT_14667_02046: 3322 buses, 571 trafos  (2.4s, ETA 808s)
[93/882] CKT_14669_04784: 1941 buses, 326 trafos  (1.4s, ETA 810s)
[94/882] CKT_14671_09092: 2769 buses, 523 trafos  (2.0s, ETA 818s)
[95/882] CKT_14672_15315: 3105 buses, 488 trafos  (2.1s, ETA 826s)
[96/882] CKT_14725_13892: 206 buses, 11 trafos  (0.1s, ETA 817s)
[97/882] CKT_1474_18780: 1944 buses, 330 trafos  (1.4s, ETA 819s)
[98/882] CKT_14781_09735: 130 buses, 10 trafos  (0.1s, ETA 811s)
[99/882] CKT_1479_18815: 417 buses, 42 trafos  (0.2s, ETA 803s)
[100/882] CKT_14848_06201: 3367 buses, 698 trafos  (2.8s, ETA 816s)
[101/882] CKT_1484_18843: 528 buses, 73 trafos  (0.4s, ETA 810s)
[102/882] CKT_14899_11561: 427 buses, 40 trafos  (0.3s, ETA 803s)
[103/882] CKT_14900_11751: 1029 buses, 86 trafos  (0.8s, ETA 801s)
[104/882] CKT_1492_13758: 1870 buses, 264 trafos  (1.5s, ETA 803s)
[105/882] CKT_1493_13760: 498 buses, 95 trafos  (0.7s, ETA 799s)
[106/882] CKT_14974_11641: 464 buses, 33 trafos  (0.2s, ETA 793s)
[107/882] CKT_1501_13791: 2599 buses, 474 trafos  (2.0s, ETA 799s)
[108/882] CKT_1502_13795: 2111 buses, 322 trafos  (1.3s, ETA 800s)
[109/882] CKT_1507_13820: 2748 buses, 498 trafos  (2.1s, ETA 806s)
[110/882] CKT_1516_13854: 3201 buses, 647 trafos  (2.7s, ETA 817s)
[111/882] CKT_1521_13870: 1413 buses, 248 trafos  (1.0s, ETA 815s)
[112/882] CKT_1532_16308: 147 buses, 10 trafos  (0.1s, ETA 808s)
[113/882] CKT_1533_16310: 3850 buses, 685 trafos  (3.5s, ETA 823s)
[114/882] CKT_1540_16334: 1613 buses, 286 trafos  (1.0s, ETA 822s)
[115/882] CKT_1547_16352: 1444 buses, 210 trafos  (1.1s, ETA 821s)
[116/882] CKT_1550_16359: 1413 buses, 234 trafos  (0.9s, ETA 818s)
[117/882] CKT_1561_16404: 2611 buses, 472 trafos  (1.9s, ETA 823s)
[118/882] CKT_156_06131: 1647 buses, 174 trafos  (1.2s, ETA 822s)
[119/882] CKT_1570_18871: 1144 buses, 176 trafos  (1.0s, ETA 821s)
[120/882] CKT_1578_18929: 1671 buses, 288 trafos  (1.1s, ETA 820s)
[121/882] CKT_1581_18950: 1191 buses, 198 trafos  (1.1s, ETA 819s)
[122/882] CKT_15_17454: 1946 buses, 194 trafos  (0.9s, ETA 817s)
[123/882] CKT_1611_13930: 280 buses, 29 trafos  (0.2s, ETA 810s)
[124/882] CKT_1616_13918: 4002 buses, 617 trafos  (2.5s, ETA 818s)
[125/882] CKT_1620_13959: 1448 buses, 217 trafos  (0.8s, ETA 815s)
[126/882] CKT_1621_13960: 980 buses, 179 trafos  (0.8s, ETA 813s)
[127/882] CKT_1626_13982: 341 buses, 26 trafos  (0.2s, ETA 806s)
[128/882] CKT_1636_14037: 1875 buses, 333 trafos  (1.2s, ETA 806s)
[129/882] CKT_1637_14047: 2768 buses, 513 trafos  (2.1s, ETA 811s)
[130/882] CKT_1649_16455: 1401 buses, 264 trafos  (1.2s, ETA 810s)
[131/882] CKT_164_06887: 1937 buses, 225 trafos  (1.0s, ETA 809s)
[132/882] CKT_1653_16461: 914 buses, 134 trafos  (0.5s, ETA 804s)
[133/882] CKT_1658_16472: 1412 buses, 229 trafos  (1.1s, ETA 803s)
[134/882] CKT_165_16112: 921 buses, 110 trafos  (0.5s, ETA 799s)
[135/882] CKT_1660_16476: 1369 buses, 237 trafos  (0.9s, ETA 797s)
[136/882] CKT_1663_16490: 2961 buses, 575 trafos  (2.3s, ETA 803s)
[137/882] CKT_166_17692: 1050 buses, 135 trafos  (0.6s, ETA 799s)
[138/882] CKT_1674_16535: 1332 buses, 232 trafos  (1.0s, ETA 797s)
[139/882] CKT_1678_16550: 1343 buses, 195 trafos  (0.8s, ETA 795s)
[140/882] CKT_167_03257: 775 buses, 103 trafos  (0.4s, ETA 790s)
[141/882] CKT_1680_19100: 1091 buses, 111 trafos  (0.5s, ETA 786s)
[142/882] CKT_1685_19133: 840 buses, 130 trafos  (0.6s, ETA 783s)
[143/882] CKT_1689_19139: 1071 buses, 152 trafos  (0.6s, ETA 780s)
[144/882] CKT_168_12024: 1406 buses, 199 trafos  (0.8s, ETA 777s)
[145/882] CKT_1693_19140: 1533 buses, 246 trafos  (1.1s, ETA 776s)
[146/882] CKT_1695_19150: 1680 buses, 309 trafos  (1.2s, ETA 776s)
[147/882] CKT_169_11022: 1578 buses, 204 trafos  (0.9s, ETA 774s)
[148/882] CKT_16_01377: 2140 buses, 249 trafos  (1.2s, ETA 774s)
[149/882] CKT_1707_19230: 511 buses, 72 trafos  (0.4s, ETA 769s)
[150/882] CKT_170_07251: 1767 buses, 324 trafos  (1.2s, ETA 769s)
[151/882] CKT_1711_19245: 2048 buses, 262 trafos  (1.4s, ETA 770s)
[152/882] CKT_1718_19268: 171 buses, 16 trafos  (0.1s, ETA 764s)
[153/882] CKT_171_08161: 1809 buses, 310 trafos  (1.1s, ETA 764s)
[154/882] CKT_1727_14043: 3213 buses, 404 trafos  (1.9s, ETA 766s)
[155/882] CKT_1729_14074: 1901 buses, 238 trafos  (1.0s, ETA 765s)
[156/882] CKT_172_04726: 4843 buses, 882 trafos  (3.6s, ETA 776s)
[157/882] CKT_1731_14082: 148 buses, 8 trafos  (0.1s, ETA 770s)
[158/882] CKT_173_13082: 1517 buses, 262 trafos  (0.9s, ETA 768s)
[159/882] CKT_1742_14134: 2015 buses, 384 trafos  (1.6s, ETA 770s)
[160/882] CKT_1747_14145: 223 buses, 4 trafos  (0.1s, ETA 764s)
[161/882] CKT_1750_14152: 4032 buses, 768 trafos  (3.0s, ETA 772s)
[162/882] CKT_1753_14154: 339 buses, 39 trafos  (0.4s, ETA 768s)
[163/882] CKT_175_19176: 1441 buses, 245 trafos  (0.9s, ETA 766s)
[164/882] CKT_1762_14178: 2745 buses, 442 trafos  (2.0s, ETA 770s)
[165/882] CKT_1763_14181: 749 buses, 125 trafos  (0.5s, ETA 766s)
[166/882] CKT_1776_16585: 1706 buses, 200 trafos  (0.9s, ETA 764s)
[167/882] CKT_1777_16587: 43 buses, 4 trafos  (0.1s, ETA 759s)
[168/882] CKT_1787_16600: 4441 buses, 791 trafos  (4.2s, ETA 771s)
[169/882] CKT_178_11012: 1645 buses, 286 trafos  (1.5s, ETA 772s)
[170/882] CKT_1793_16665: 1896 buses, 331 trafos  (1.3s, ETA 772s)
[171/882] CKT_1806_19309: 279 buses, 41 trafos  (0.2s, ETA 767s)
[172/882] CKT_1809_19340: 108 buses, 19 trafos  (0.1s, ETA 762s)
[173/882] CKT_1812_19354: 1319 buses, 177 trafos  (0.7s, ETA 760s)
[174/882] CKT_1814_19370: 637 buses, 95 trafos  (0.5s, ETA 757s)
[175/882] CKT_1815_19373: 1099 buses, 211 trafos  (0.8s, ETA 754s)
[176/882] CKT_1824_19417: 1205 buses, 205 trafos  (0.8s, ETA 752s)
[177/882] CKT_1828_19450: 1019 buses, 168 trafos  (1.0s, ETA 751s)
[178/882] CKT_1833_19537: 3186 buses, 517 trafos  (7.4s, ETA 775s)
[179/882] CKT_1835_19528: 3589 buses, 570 trafos  (9.1s, ETA 805s)
[180/882] CKT_1842_19300: 624 buses, 106 trafos  (1.7s, ETA 806s)
[181/882] CKT_1850_11363: 2123 buses, 265 trafos  (4.8s, ETA 819s)
[182/882] CKT_1854_10333: 1716 buses, 320 trafos  (5.5s, ETA 835s)
[183/882] CKT_1858_15372: 1802 buses, 262 trafos  (4.4s, ETA 846s)
[184/882] CKT_1859_02323: 452 buses, 75 trafos  (1.3s, ETA 845s)
[185/882] CKT_1860_11041: 1140 buses, 206 trafos  (3.3s, ETA 851s)
[186/882] CKT_1868_04422: 2501 buses, 448 trafos  (6.7s, ETA 871s)
[187/882] CKT_1878_14004: 1726 buses, 195 trafos  (3.4s, ETA 878s)
[188/882] CKT_1879_16763: 928 buses, 133 trafos  (2.4s, ETA 880s)
[189/882] CKT_1880_19785: 945 buses, 129 trafos  (2.0s, ETA 882s)
[190/882] CKT_1896_00669: 1960 buses, 343 trafos  (3.0s, ETA 887s)
[191/882] CKT_189_10931: 1200 buses, 178 trafos  (0.8s, ETA 884s)
[192/882] CKT_18_03353: 5071 buses, 705 trafos  (2.9s, ETA 889s)
[193/882] CKT_1905_00695: 610 buses, 102 trafos  (0.4s, ETA 884s)
[194/882] CKT_1906_00698: 416 buses, 48 trafos  (0.2s, ETA 879s)
[195/882] CKT_1908_00705: 2303 buses, 304 trafos  (1.1s, ETA 877s)
[196/882] CKT_1909_00720: 1667 buses, 273 trafos  (1.1s, ETA 875s)
[197/882] CKT_1911_00726: 2613 buses, 263 trafos  (1.0s, ETA 873s)
[198/882] CKT_1914_00740: 663 buses, 114 trafos  (0.4s, ETA 869s)
[199/882] CKT_1948_00927: 1219 buses, 183 trafos  (0.8s, ETA 866s)
[200/882] CKT_1957_00990: 3158 buses, 501 trafos  (1.7s, ETA 866s)
[201/882] CKT_1959_01030: 1360 buses, 230 trafos  (1.0s, ETA 864s)
[202/882] CKT_195_05626: 337 buses, 29 trafos  (0.2s, ETA 859s)
[203/882] CKT_1960_01040: 889 buses, 132 trafos  (0.5s, ETA 855s)
[204/882] CKT_1962_01050: 488 buses, 55 trafos  (0.2s, ETA 850s)
[205/882] CKT_1963_01510: 908 buses, 116 trafos  (0.5s, ETA 846s)
[206/882] CKT_1964_01053: 2140 buses, 351 trafos  (1.7s, ETA 846s)
[207/882] CKT_196_19261: 1032 buses, 187 trafos  (0.9s, ETA 844s)
[208/882] CKT_197_14709: 467 buses, 61 trafos  (0.4s, ETA 840s)
[209/882] CKT_2002_01096: 173 buses, 19 trafos  (0.1s, ETA 835s)
[210/882] CKT_2004_01140: 341 buses, 34 trafos  (0.3s, ETA 831s)
[211/882] CKT_2018_01231: 1193 buses, 193 trafos  (1.1s, ETA 829s)
[212/882] CKT_2021_01251: 787 buses, 112 trafos  (0.7s, ETA 826s)
[213/882] CKT_2023_01255: 1672 buses, 297 trafos  (1.6s, ETA 826s)
[214/882] CKT_2025_17258: 5930 buses, 1216 trafos  (4.7s, ETA 836s)
[215/882] CKT_2037_00805: 1157 buses, 172 trafos  (0.7s, ETA 833s)
[216/882] CKT_2039_00814: 1397 buses, 181 trafos  (0.9s, ETA 830s)
[217/882] CKT_2041_00816: 262 buses, 32 trafos  (0.2s, ETA 826s)
[218/882] CKT_2045_00830: 1522 buses, 250 trafos  (0.9s, ETA 823s)
[219/882] CKT_2053_00870: 1908 buses, 270 trafos  (1.0s, ETA 822s)
[220/882] CKT_2055_00878: 1674 buses, 234 trafos  (1.3s, ETA 820s)
[221/882] CKT_2063_11843: 985 buses, 145 trafos  (0.6s, ETA 817s)
[222/882] CKT_2074_11907: 1575 buses, 245 trafos  (1.0s, ETA 815s)
[223/882] CKT_2079_11915: 2414 buses, 446 trafos  (1.8s, ETA 816s)
[224/882] CKT_2080_11920: 1699 buses, 256 trafos  (1.0s, ETA 814s)
[225/882] CKT_2082_11931: 781 buses, 103 trafos  (0.5s, ETA 810s)
[226/882] CKT_2083_11935: 440 buses, 53 trafos  (0.5s, ETA 807s)
[227/882] CKT_2093_11975: 1048 buses, 126 trafos  (0.5s, ETA 804s)
[228/882] CKT_209_14375: 1170 buses, 203 trafos  (0.8s, ETA 801s)
[229/882] CKT_2107_12058: 1757 buses, 229 trafos  (0.9s, ETA 799s)
[230/882] CKT_2109_12070: 1088 buses, 165 trafos  (0.8s, ETA 797s)
[231/882] CKT_210_14376: 1117 buses, 183 trafos  (0.7s, ETA 794s)
[232/882] CKT_2112_12083: 1272 buses, 228 trafos  (0.8s, ETA 792s)
[233/882] CKT_2116_12100: 686 buses, 87 trafos  (0.4s, ETA 788s)
[234/882] CKT_2120_12131: 1235 buses, 217 trafos  (1.1s, ETA 787s)
[235/882] CKT_2127_12159: 1504 buses, 238 trafos  (0.9s, ETA 785s)
[236/882] CKT_2132_12175: 1632 buses, 262 trafos  (1.0s, ETA 783s)
[237/882] CKT_2135_12198: 3236 buses, 357 trafos  (1.7s, ETA 783s)
[238/882] CKT_2141_12243: 1011 buses, 141 trafos  (0.6s, ETA 780s)
[239/882] CKT_2150_12317: 41 buses, 4 trafos  (0.1s, ETA 776s)
[240/882] CKT_2155_12331: 1591 buses, 306 trafos  (1.1s, ETA 774s)
[241/882] CKT_2163_12395: 1740 buses, 265 trafos  (1.4s, ETA 774s)
[242/882] CKT_2169_12425: 3021 buses, 566 trafos  (2.2s, ETA 775s)
[243/882] CKT_2170_12430: 1951 buses, 299 trafos  (1.4s, ETA 774s)
[244/882] CKT_217_14397: 1282 buses, 221 trafos  (0.8s, ETA 772s)
[245/882] CKT_2186_12523: 1375 buses, 228 trafos  (0.9s, ETA 770s)
[246/882] CKT_218_14401: 3267 buses, 381 trafos  (1.8s, ETA 770s)
[247/882] CKT_2194_12564: 1766 buses, 278 trafos  (1.1s, ETA 769s)
[248/882] CKT_2198_12582: 1560 buses, 297 trafos  (1.3s, ETA 768s)
[249/882] CKT_2200_12600: 571 buses, 90 trafos  (0.7s, ETA 765s)
[250/882] CKT_2204_12616: 1512 buses, 267 trafos  (1.2s, ETA 764s)
[251/882] CKT_2210_12690: 2787 buses, 558 trafos  (2.7s, ETA 767s)
[252/882] CKT_2211_12700: 944 buses, 162 trafos  (0.6s, ETA 764s)
[253/882] CKT_2219_12716: 315 buses, 28 trafos  (0.2s, ETA 760s)
[254/882] CKT_2226_16240: 883 buses, 136 trafos  (0.5s, ETA 757s)
[255/882] CKT_2248_08360: 1551 buses, 231 trafos  (0.8s, ETA 755s)
[256/882] CKT_2251_01518: 1182 buses, 168 trafos  (0.7s, ETA 753s)
[257/882] CKT_2267_10417: 1813 buses, 328 trafos  (1.5s, ETA 752s)
[258/882] CKT_226_14436: 651 buses, 106 trafos  (0.5s, ETA 749s)
[259/882] CKT_2282_09320: 3530 buses, 648 trafos  (2.8s, ETA 752s)
[260/882] CKT_2287_04045: 1915 buses, 265 trafos  (1.1s, ETA 750s)
[261/882] CKT_2290_08949: 2704 buses, 451 trafos  (2.1s, ETA 751s)
[262/882] CKT_2292_10360: 2137 buses, 320 trafos  (1.2s, ETA 750s)
[263/882] CKT_2298_01744: 1518 buses, 256 trafos  (1.0s, ETA 748s)
[264/882] CKT_229_14450: 2296 buses, 391 trafos  (1.8s, ETA 748s)
[265/882] CKT_2301_08405: 2587 buses, 427 trafos  (1.6s, ETA 748s)
[266/882] CKT_2305_02600: 105 buses, 9 trafos  (0.1s, ETA 744s)
[267/882] CKT_2306_03990: 1023 buses, 185 trafos  (0.7s, ETA 742s)
[268/882] CKT_2307_04980: 1596 buses, 251 trafos  (1.2s, ETA 741s)
[269/882] CKT_2308_05190: 1519 buses, 248 trafos  (1.0s, ETA 739s)
[270/882] CKT_2309_07370: 1916 buses, 267 trafos  (1.5s, ETA 739s)
[271/882] CKT_2315_04795: 1898 buses, 276 trafos  (1.2s, ETA 737s)
[272/882] CKT_2316_05502: 393 buses, 49 trafos  (0.2s, ETA 734s)
[273/882] CKT_2317_06108: 740 buses, 107 trafos  (0.4s, ETA 731s)
[274/882] CKT_2319_01846: 1791 buses, 321 trafos  (1.5s, ETA 730s)
[275/882] CKT_2339_03090: 196 buses, 32 trafos  (0.2s, ETA 727s)
[276/882] CKT_2340_10500: 1968 buses, 358 trafos  (1.3s, ETA 726s)
[277/882] CKT_2342_01960: 1998 buses, 374 trafos  (1.7s, ETA 726s)
[278/882] CKT_2343_02490: 1736 buses, 322 trafos  (1.2s, ETA 725s)
[279/882] CKT_2344_02640: 2008 buses, 386 trafos  (1.5s, ETA 724s)
[280/882] CKT_2345_10420: 1195 buses, 212 trafos  (1.1s, ETA 723s)
[281/882] CKT_2352_01810: 939 buses, 157 trafos  (0.6s, ETA 720s)
[282/882] CKT_2353_02370: 1225 buses, 205 trafos  (0.8s, ETA 718s)
[283/882] CKT_2354_05310: 1546 buses, 292 trafos  (1.1s, ETA 717s)
[284/882] CKT_2355_08510: 807 buses, 133 trafos  (0.8s, ETA 715s)
[285/882] CKT_2356_03680: 1409 buses, 253 trafos  (0.9s, ETA 713s)
[286/882] CKT_2357_04160: 936 buses, 154 trafos  (0.6s, ETA 711s)
[287/882] CKT_2358_08750: 1068 buses, 179 trafos  (0.7s, ETA 709s)
[288/882] CKT_2359_11720: 1214 buses, 214 trafos  (1.0s, ETA 707s)
[289/882] CKT_2360_01350: 1085 buses, 209 trafos  (0.8s, ETA 705s)
[290/882] CKT_2361_02510: 2338 buses, 371 trafos  (1.4s, ETA 704s)
[291/882] CKT_2362_07346: 940 buses, 142 trafos  (0.6s, ETA 702s)
[292/882] CKT_2363_01629: 2051 buses, 271 trafos  (1.4s, ETA 701s)
[293/882] CKT_2380_07900: 63 buses, 8 trafos  (0.1s, ETA 698s)
[294/882] CKT_2381_04723: 2032 buses, 274 trafos  (1.2s, ETA 696s)
[295/882] CKT_2382_06504: 2690 buses, 394 trafos  (1.8s, ETA 696s)
[296/882] CKT_2388_10600: 398 buses, 59 trafos  (0.3s, ETA 693s)
[297/882] CKT_2403_05307: 950 buses, 150 trafos  (0.7s, ETA 691s)
[298/882] CKT_2404_07490: 2175 buses, 389 trafos  (1.4s, ETA 690s)
[299/882] CKT_2405_09355: 908 buses, 115 trafos  (0.5s, ETA 688s)
[300/882] CKT_2410_09443: 1854 buses, 305 trafos  (1.4s, ETA 687s)
[301/882] CKT_2412_05810: 2895 buses, 566 trafos  (2.2s, ETA 688s)
[302/882] CKT_2414_04770: 2453 buses, 480 trafos  (2.1s, ETA 689s)

In [3]:
# --- Show buses where CYME would NOT have an explicit base voltage ---
# These are buses that are neither source nor transformer LV buses.
# CYME inherits voltage from upstream; mc always uses explicit vn_kv.
unset_buses = df_all_buses[df_all_buses['CYME_UserDefinedBaseVoltage'] == 'inherited/unset']
print(f"Buses WITHOUT explicit CYME UserDefinedBaseVoltage: {len(unset_buses)} / {len(df_all_buses)}")
print(f"Buses WITH explicit CYME voltage (source + trafo LV): {len(df_all_buses) - len(unset_buses)}")
print()

# Show per-circuit summary
voltage_summary = df_all_buses.groupby('CKT_KEY').agg(
    n_buses=('BUS_IDX', 'count'),
    n_source=('IS_SOURCE', 'sum'),
    n_trafo_lv=('IS_TRAFO_LV', 'sum'),
    n_cyme_unset=('CYME_UserDefinedBaseVoltage', lambda x: (x == 'inherited/unset').sum()),
    voltage_levels=('MC_VN_KV (L-L)', lambda x: sorted(x.unique().tolist())),
).reset_index()
voltage_summary

Buses WITHOUT explicit CYME UserDefinedBaseVoltage: 1151750 / 1373822
Buses WITH explicit CYME voltage (source + trafo LV): 222072

,CKT_KEY,n_buses,n_source,n_trafo_lv,n_cyme_unset,voltage_levels
0,CKT_100_16795,2067,1,374,1692,"[0.12, 0.24, 0.277, 12.0]"
1,CKT_1014_17972,3361,1,681,2679,"[0.12, 0.24, 0.277, 12.0]"
2,CKT_1019_17995,1578,1,293,1284,"[0.12, 0.24, 0.277, 12.0]"
3,CKT_1021_18000,1518,1,274,1243,"[0.12, 0.24, 0.277, 2.4, 12.0]"
4,CKT_1025_18018,1866,1,308,1557,"[0.12, 0.24, 0.277, 12.0]"
...,...,...,...,...,...,...
877,CKT_9177_03165,1107,1,130,976,"[0.12, 0.277, 12.0]"
878,CKT_9208_09357,1611,1,240,1370,"[0.104, 0.12, 0.277, 12.0]"
879,CKT_922_17915,4270,1,777,3492,"[0.12, 0.24, 0.277, 12.0]"
880,CKT_925_17912,814,1,124,689,"[0.12, 0.24, 0.277, 12.0]"
881,CKT_92_16775,1008,1,159,848,"[0.12, 0.277, 2.4, 16.0]"

In [4]:
# --- Transformer configuration comparison ---
print("=== TRANSFORMER CONNECTION TYPE COMPARISON ===\n")

if not df_all_trafos.empty:
    # Ensure calculated-secondary comparison fields are present even if the main build cell was interrupted.
    if 'CALCULATED_TRANSFORMER_SECONDARY_LL_KV' not in df_all_trafos.columns:
        if 'CALCULATED_SecondaryV (L-L)' in df_all_trafos.columns:
            df_all_trafos['CALCULATED_TRANSFORMER_SECONDARY_LL_KV'] = df_all_trafos['CALCULATED_SecondaryV (L-L)']
        else:
            lv_conn = df_all_trafos['MC_CONNECTION (derived)'].astype(str).str.split('_').str[-1]
            lv_w = pd.to_numeric(df_all_trafos.get('MC_LV_WINDING_KV', np.nan), errors='coerce')
            df_all_trafos['CALCULATED_TRANSFORMER_SECONDARY_LL_KV'] = np.where(
                lv_conn.eq('Y'), lv_w * np.sqrt(3), np.where(lv_conn.eq('D'), lv_w, np.nan)
            )

    if 'CYME_SecondaryV (L-L)' not in df_all_trafos.columns:
        df_all_trafos['CYME_SecondaryV (L-L)'] = pd.to_numeric(df_all_trafos.get('LV_BUS_VN_KV', np.nan), errors='coerce')

    calc_sec = pd.to_numeric(df_all_trafos['CALCULATED_TRANSFORMER_SECONDARY_LL_KV'], errors='coerce')
    bus_sec = pd.to_numeric(df_all_trafos.get('LV_BUS_VN_KV', np.nan), errors='coerce')
    cyme_sec = pd.to_numeric(df_all_trafos.get('CYME_SecondaryV (L-L)', np.nan), errors='coerce')

    df_all_trafos['DELTA_CALC_TO_BUS_KV'] = calc_sec - bus_sec
    df_all_trafos['DELTA_CALC_TO_CYME_KV'] = calc_sec - cyme_sec

    tol_kv = 0.01
    df_all_trafos['CALC_vs_BUS_MATCH'] = calc_sec.notna() & bus_sec.notna() & (df_all_trafos['DELTA_CALC_TO_BUS_KV'].abs() <= tol_kv)
    df_all_trafos['CALC_vs_CYME_MATCH'] = calc_sec.notna() & cyme_sec.notna() & (df_all_trafos['DELTA_CALC_TO_CYME_KV'].abs() <= tol_kv)
    df_all_trafos['SECONDARY_VOLTAGE_ALL_MATCH'] = df_all_trafos['CALC_vs_BUS_MATCH'] & df_all_trafos['CALC_vs_CYME_MATCH']

    # Show connection mismatches (mc derived vs CYME simplified)
    mismatches = df_all_trafos[df_all_trafos['CONNECTION_MATCH'] == False]
    print(f"Connection type mismatches: {len(mismatches)} / {len(df_all_trafos)} transformers")
    if not mismatches.empty:
        print("\nMismatched transformers:")
        base_cols = ['CKT_KEY', 'TRAFO_IDX', 'MC_CONNECTION (derived)', 'CYME_CONNECTION']
        phase_cols = [c for c in ['MC_HV_TO_PHASES', 'MC_LV_TO_PHASES', 'MC_FROM_PHASES', 'MC_TO_PHASES'] if c in mismatches.columns]
        print(mismatches[base_cols + phase_cols].to_string(index=False))

    print(f"\n\n=== SECONDARY VOLTAGE MATCH CHECK ===")
    v_mismatch = df_all_trafos[df_all_trafos['SECONDARY_VOLTAGE_ALL_MATCH'] == False]
    print(f"Secondary voltage mismatches: {len(v_mismatch)} / {len(df_all_trafos)} transformers")
    if not v_mismatch.empty:
        print(v_mismatch[['CKT_KEY', 'TRAFO_IDX', 'LV_BUS_VN_KV', 'MC_LV_WINDING_KV',
                          'CALCULATED_TRANSFORMER_SECONDARY_LL_KV', 'CYME_SecondaryV (L-L)',
                          'DELTA_CALC_TO_BUS_KV', 'DELTA_CALC_TO_CYME_KV',
                          'CALC_vs_BUS_MATCH', 'CALC_vs_CYME_MATCH']].head(50).to_string(index=False))

    print(f"\n\n=== CYME CONNECTION DISTRIBUTION ===")
    print(df_all_trafos['CYME_CONNECTION'].value_counts())
    print(f"\n=== MC CONNECTION DISTRIBUTION ===")
    print(df_all_trafos['MC_CONNECTION (derived)'].value_counts())

    # Impedance comparison: mc stores half-impedance per side,
    # but mc_to_cyme.py feeds vk_percent directly as CYME Z1%.
    # CYME expects TOTAL positive-sequence impedance.
    # If mc has vk/2 and CYME gets vk/2 as "total", the impedance is HALVED.
    print(f"\n\n=== IMPEDANCE ANALYSIS ===")
    print("MC stores vk_percent as HALF the total (split between HV and LV sides).")
    print("mc_to_cyme.py feeds this half-value directly to CYME as PositiveSequenceImpedancePercent.")
    print("This means CYME sees HALF the actual transformer impedance!\n")

    imp_summary = df_all_trafos[['CKT_KEY', 'TRAFO_IDX', 'MC_VK_PCT (per side)',
                                 'CYME_Z1_PCT (fed as-is from mc)', 'MC_TOTAL_SN_MVA', 'CYME_RatingKVA']].copy()
    imp_summary['CORRECT_TOTAL_Z1_PCT'] = imp_summary['MC_VK_PCT (per side)'] * 2
    imp_summary['Z_ERROR_FACTOR'] = 0.5  # CYME gets half the impedance
    imp_summary
else:
    print("No transformers found in the loaded networks.")

=== TRANSFORMER CONNECTION TYPE COMPARISON ===

Connection type mismatches: 23950 / 221201 transformers

Mismatched transformers:
           CKT_KEY  TRAFO_IDX MC_CONNECTION (derived) CYME_CONNECTION MC_HV_TO_PHASES MC_LV_TO_PHASES     MC_FROM_PHASES       MC_TO_PHASES
     CKT_100_16795         49                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795         59                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795         60                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795         63                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795         65                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795         69                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795         70                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795         71                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795         72                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795         73                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795         80                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795         82                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795         83                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795         84                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795         86                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795         87                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795         92                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795         93                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795         98                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        105                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        111                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        112                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        115                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        116                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        117                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        118                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        119                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        120                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        121                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        124                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        126                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        128                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        129                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        130                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        132                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        133                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        134                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        135                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        136                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        137                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        138                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        139                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        140                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        147                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        150                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        151                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        153                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        156                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        159                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        161                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        162                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        163                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        165                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        167                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        168                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        175                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        179                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        180                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        184                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        194                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        197                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        219                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        220                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        234                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        235                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        236                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        237                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        238                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        244                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        246                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        252                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        253                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        257                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        258                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        263                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        264                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        265                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        266                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        268                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        285                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        286                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        290                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        291                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        293                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        296                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        299                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        300                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        310                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        311                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        327                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        344                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
     CKT_100_16795        354                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        367                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
     CKT_100_16795        369                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
    CKT_1014_17972         59                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
    CKT_1014_17972         80                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
    CKT_1014_17972         81                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
    CKT_1014_17972         82                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
    CKT_1014_17972         85                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972         93                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972         94                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        109                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        116                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        118                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        123                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        124                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        125                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
    CKT_1014_17972        126                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        129                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        130                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        132                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        134                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        140                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        143                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        172                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        173                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        174                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        175                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        196                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        199                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        205                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        206                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
    CKT_1014_17972        207                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        216                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        217                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        275                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
    CKT_1014_17972        351                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        417                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        431                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        474                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        478                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        489                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        528                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1014_17972        571                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
    CKT_1014_17972        605                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1019_17995        111                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1019_17995        147                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1019_17995        165                     D_D            D_Yg       [B, C, A]       [B, C, A] [A, B, C, A, B, C] [B, C, A, B, C, A]
    CKT_1019_17995        235                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]
    CKT_1021_18000          3                     Y_D            D_Yg       [N, N, N]       [B, C, A] [A, B, C, A, B, C] [B, C, A, N, N, N]

In [5]:
v_mismatch

,CKT_KEY,TRAFO_IDX,HV_BUS,LV_BUS,HV_BUS_VN_KV,LV_BUS_VN_KV,MC_HV_WINDING_KV,MC_LV_WINDING_KV,MC_CONNECTION (derived),CYME_CONNECTION,...,CALCULATED_SecondaryV (L-L),CALC_vs_BUS_MATCH,CALC_vs_CYME_MATCH,SECONDARY_VOLTAGE_ALL_MATCH,CYME_RatingKVA,MC_TAP_POS,N_CIRCUITS,CALCULATED_TRANSFORMER_SECONDARY_LL_KV,DELTA_CALC_TO_BUS_KV,DELTA_CALC_TO_CYME_KV
63,CKT_100_16795,63,841,1394,12.0,0.12,12.0,0.069282,D_D,D_Yg,...,0.069282,False,False,False,16.666667,0.0,6,0.069282,-0.050718,-0.050718
71,CKT_100_16795,71,929,1923,12.0,0.12,12.0,0.069282,D_D,D_Yg,...,0.069282,False,False,False,6.666667,0.0,6,0.069282,-0.050718,-0.050718
72,CKT_100_16795,72,1127,1139,12.0,0.12,12.0,0.069282,D_D,D_Yg,...,0.069282,False,False,False,16.666667,0.0,6,0.069282,-0.050718,-0.050718
73,CKT_100_16795,73,155,654,12.0,0.12,12.0,0.069282,D_D,D_Yg,...,0.069282,False,False,False,16.666667,0.0,6,0.069282,-0.050718,-0.050718
86,CKT_100_16795,86,743,1872,12.0,0.12,12.0,0.069282,D_D,D_Yg,...,0.069282,False,False,False,16.666667,0.0,6,0.069282,-0.050718,-0.050718
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221169,CKT_92_16775,127,420,522,16.0,0.12,16.0,0.069282,D_D,D_Yg,...,0.069282,False,False,False,10.000000,0.0,6,0.069282,-0.050718,-0.050718
221170,CKT_92_16775,128,584,610,16.0,0.12,16.0,0.069282,D_D,D_Yg,...,0.069282,False,False,False,25.000000,0.0,6,0.069282,-0.050718,-0.050718
221182,CKT_92_16775,140,286,372,16.0,0.12,16.0,0.069282,D_D,D_Yg,...,0.069282,False,False,False,25.000000,0.0,6,0.069282,-0.050718,-0.050718
221183,CKT_92_16775,141,731,932,16.0,0.12,16.0,0.069282,D_D,D_Yg,...,0.069282,False,False,False,15.000000,0.0,6,0.069282,-0.050718,-0.050718
221200,CKT_92_16775,158,172,251,16.0,0.12,16.0,0.069282,D_D,D_Yg,...,0.069282,False,False,False,13.333333,0.0,6,0.069282,-0.050718,-0.050718

In [16]:
df_all_trafos

,CKT_KEY,TRAFO_IDX,HV_BUS,LV_BUS,HV_BUS_VN_KV,LV_BUS_VN_KV,MC_HV_WINDING_KV,MC_LV_WINDING_KV,MC_CONNECTION (derived),CYME_CONNECTION,...,CALCULATED_SecondaryV (L-L),CALC_vs_BUS_MATCH,CALC_vs_CYME_MATCH,SECONDARY_VOLTAGE_ALL_MATCH,CYME_RatingKVA,MC_TAP_POS,N_CIRCUITS,CALCULATED_TRANSFORMER_SECONDARY_LL_KV,DELTA_CALC_TO_BUS_KV,DELTA_CALC_TO_CYME_KV
0,CKT_100_16795,0,385,804,0.120,12.00,0.069282,6.928200,Y_Y,Yg_Yg,...,11.999994,True,True,True,37.500000,0.0,4,11.999994,-0.000006,-0.000006
1,CKT_100_16795,1,223,1395,0.120,12.00,0.069282,6.928200,Y_Y,Yg_Yg,...,11.999994,True,True,True,37.500000,0.0,4,11.999994,-0.000006,-0.000006
2,CKT_100_16795,2,1245,1411,12.000,0.12,6.928200,0.069282,Y_Y,Yg_Yg,...,0.120000,True,True,True,37.500000,0.0,4,0.120000,0.000000,0.000000
3,CKT_100_16795,3,1168,1800,12.000,0.12,6.928200,0.069282,Y_Y,Yg_Yg,...,0.120000,True,True,True,12.500000,0.0,4,0.120000,0.000000,0.000000
4,CKT_100_16795,4,1848,2009,0.277,12.00,0.159926,6.928200,Y_Y,Yg_Yg,...,11.999994,True,True,True,12.500000,0.0,4,11.999994,-0.000006,-0.000006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221196,CKT_92_16775,154,533,674,16.000,0.12,9.237600,0.069282,Y_Y,Yg_Yg,...,0.120000,True,True,True,7.500000,0.0,4,0.120000,0.000000,0.000000
221197,CKT_92_16775,155,315,367,0.120,16.00,0.069282,9.237600,Y_Y,Yg_Yg,...,15.999993,True,True,True,25.000000,0.0,4,15.999993,-0.000007,-0.000007
221198,CKT_92_16775,156,93,484,0.120,16.00,0.069282,9.237600,Y_Y,Yg_Yg,...,15.999993,True,True,True,25.000000,0.0,4,15.999993,-0.000007,-0.000007
221199,CKT_92_16775,157,688,951,16.000,0.12,9.237600,0.069282,Y_Y,Yg_Yg,...,0.120000,True,True,True,7.500000,0.0,4,0.120000,0.000000,0.000000
221200,CKT_92_16775,158,172,251,16.000,0.12,16.000000,0.069282,D_D,D_Yg,...,0.069282,False,False,False,13.333333,0.0,6,0.069282,-0.050718,-0.050718

In [ ]:
# --- Voltage discrepancy analysis: buses with different voltage levels ---
# Vectorized summary instead of per-circuit print loop

print("=== BUS VOLTAGE LEVEL ANALYSIS ===\n")

# Per-circuit summary via groupby (fast)
voltage_analysis = df_all_buses.groupby('CKT_KEY').agg(
    n_buses=('BUS_IDX', 'count'),
    n_source=('IS_SOURCE', 'sum'),
    n_trafo_lv=('IS_TRAFO_LV', 'sum'),
    voltage_levels=('MC_VN_KV (L-L)', lambda x: sorted(x.unique().tolist())),
    n_voltage_levels=('MC_VN_KV (L-L)', 'nunique'),
    source_voltage=('MC_VN_KV (L-L)', lambda x: x[df_all_buses.loc[x.index, 'IS_SOURCE']].unique().tolist()),
).reset_index()

# Regular (non-source, non-trafo-LV) bus voltage distribution per circuit
regular_mask = ~df_all_buses['IS_SOURCE'] & ~df_all_buses['IS_TRAFO_LV']
regular_vcount = (
    df_all_buses[regular_mask]
    .groupby(['CKT_KEY', 'MC_VN_KV (L-L)'])
    .size()
    .reset_index(name='count')
    .groupby('CKT_KEY')
    .apply(lambda g: dict(zip(g['MC_VN_KV (L-L)'], g['count'])), include_groups=False)
    .rename('regular_buses_by_voltage')
)
voltage_analysis = voltage_analysis.merge(regular_vcount, on='CKT_KEY', how='left')

# Trafo LV bus details per circuit (replace iterrows with a grouped join)
trafo_lv_details = (
    df_all_buses[df_all_buses['IS_TRAFO_LV']]
    .groupby('CKT_KEY')
    .apply(
        lambda g: [
            f"{r['BUS_NAME']}(idx={r['BUS_IDX']}, {r['MC_VN_KV (L-L)']}kV, {r['TRAFO_NAME']})"
            for _, r in g[['BUS_NAME', 'BUS_IDX', 'MC_VN_KV (L-L)', 'TRAFO_NAME']].iterrows()
        ],
        include_groups=False,
    )
    .rename('trafo_lv_buses')
)
voltage_analysis = voltage_analysis.merge(trafo_lv_details, on='CKT_KEY', how='left')

print(f"Total circuits: {len(voltage_analysis)}")
print(f"Circuits with >2 voltage levels: {(voltage_analysis['n_voltage_levels'] > 2).sum()}")
print(f"Circuits with trafo LV buses: {(voltage_analysis['n_trafo_lv'] > 0).sum()}")
voltage_analysis

In [11]:
# --- Full transformer table for inspection ---
if not df_all_trafos.empty:
    display_cols = [
        'CKT_KEY', 'TRAFO_IDX', 'HV_BUS', 'LV_BUS',
        'HV_BUS_VN_KV', 'LV_BUS_VN_KV',
        'MC_HV_WINDING_KV', 'MC_LV_WINDING_KV',
        'MC_CONNECTION (derived)', 'CYME_CONNECTION', 'CONNECTION_MATCH',
        'MC_HV_FROM_PHASES', 'MC_HV_TO_PHASES', 'MC_LV_FROM_PHASES', 'MC_LV_TO_PHASES',
        'CALCULATED_TRANSFORMER_SECONDARY_LL_KV', 'CYME_SecondaryV (L-L)',
        'DELTA_CALC_TO_BUS_KV', 'DELTA_CALC_TO_CYME_KV',
        'CALC_vs_BUS_MATCH', 'CALC_vs_CYME_MATCH', 'SECONDARY_VOLTAGE_ALL_MATCH',
        'MC_SN_MVA_PER_CIRCUIT', 'MC_TOTAL_SN_MVA',
        'MC_VK_PCT (per side)', 'MC_VKR_PCT (per side)',
        'CYME_Z1_PCT (fed as-is from mc)', 'CYME_X1R1_RATIO',
        'CYME_RatingKVA', 'MC_TAP_POS',
    ]
    display_cols = [c for c in display_cols if c in df_all_trafos.columns]
    df_all_trafos[display_cols]

In [ ]:
# --- Power flow settings comparison: key differences that affect results ---
print("=" * 80)
print("POWER FLOW SETTINGS COMPARISON: MC vs CYME")
print("=" * 80)

differences = [
    ("Line Charging",
     "INCLUDED in Y_network admittance matrix",
     "DISABLED (IncludeLineCharging=0)",
     "CYME ignores shunt capacitance of lines → lower reactive power injection → different voltage profile"),

    ("Voltage-Sensitive Load Model",
     "Supports const_z_percent and const_i_percent per load (ZIP model)",
     "DISABLED (VoltageSensitivityLoadModel.V=0 → constant P/Q only)",
     "MC loads may have voltage-dependent behavior; CYME treats all as constant PQ"),

    ("Source Impedance",
     "Included via ext_grid_sequence R/X values in Y_source",
     "DISABLED (IncludeSourceImpedance=0)",
     "CYME treats source as ideal → source bus voltage is exact setpoint"),

    ("Line Transposition",
     "Full phase-unbalanced matrices (no transposition)",
     "DISABLED (AssumeLineTransposition=0)",
     "Both use untranspositioned lines — this is consistent"),

    ("Transformer Impedance",
     "vk_percent stored as HALF total (split HV/LV sides)",
     "Receives vk_percent directly as PositiveSequenceImpedancePercent",
     "⚠️ POSSIBLE BUG: CYME may be getting half the correct impedance if it expects total Z%"),

    ("Transformer Connection",
     "Full phase mapping via from_phase/to_phase arrays per circuit",
     "Simplified to D_Yg or Yg_Yg based on presence of non-zero to_phase",
     "Connection logic may not capture all vector group variations correctly"),

    ("Capacitor/Regulator Controls",
     "Can run iterative control loop (run_control=True)",
     "ALL controls LOCKED by default (LockSwitchedCapacitors=1, etc.)",
     "CYME locks cap banks and regulators at initial state"),

    ("Bus Base Voltage Assignment",
     "Explicit vn_kv per bus in net.bus table (set at creation time)",
     "UserDefinedBaseVoltage set only on source and transformer LV nodes; rest inherited",
     "CYME engine propagates voltage through topology; MC relies on explicit assignment"),
]

for name, mc_val, cyme_val, impact in differences:
    print(f"\n{'─' * 80}")
    print(f"  {name}")
    print(f"  MC:   {mc_val}")
    print(f"  CYME: {cyme_val}")
    print(f"  Impact: {impact}")

In [ ]:
# --- Display full bus table with voltage comparison ---
df_all_buses

In [4]:
# Quick quality check for derived MC connections
q_count = int(df_all_trafos['MC_CONNECTION (derived)'].str.contains(r'\?').sum()) if not df_all_trafos.empty else 0
print(f"Rows with '?' in MC_CONNECTION (derived): {q_count} / {len(df_all_trafos)}")
print(df_all_trafos['MC_CONNECTION (derived)'].value_counts().head(10))

Rows with '?' in MC_CONNECTION (derived): 0 / 221201
MC_CONNECTION (derived)
Y_Y    188002
Y_D     16602
D_Y     16581
D_D        16
Name: count, dtype: int64

## Update MC Transformer Configurations to Match CYME

CYME only supports **Y-Y** and **D-Y** connections. This cell converts all MC networks:
- **Y_D → Y_Y**: Change LV Delta to Wye
- **D_D → D_Y**: Change LV Delta to Wye

When converting LV from **Delta → Wye**:
1. Set `to_phase = 0` (neutral) on all LV-side rows
2. Set `from_phase = [1, 2, 3]` (standard Wye group-0 mapping)
3. Divide LV-side `vn_kv` by √3 (Delta stores L-L voltage directly; Wye stores L-L/√3)

Updated networks are saved as `.pkl` files in `networks/mc_xfmr/`.

In [1]:
import pickle, math, time, copy
from pathlib import Path
import pandas as pd
import numpy as np


def update_mc_xfmr_connections(net):
    """Update transformer configurations in an MC net so that all secondaries
    are Wye (matching CYME's Y-Y / D-Y convention).

    Transformations applied:
        Y_D  ->  Y_Y   (LV Delta -> Wye, divide LV vn_kv by sqrt(3))
        D_D  ->  D_Y   (LV Delta -> Wye, divide LV vn_kv by sqrt(3))
        Y_Y  ->  unchanged
        D_Y  ->  unchanged

    Returns a dict summarising changes: {trafo_idx: {'old': str, 'new': str}}.
    The net object is modified **in-place**.
    """
    SQRT3 = math.sqrt(3)
    changes = {}

    if "trafo1ph" not in net or net["trafo1ph"].empty:
        return changes

    trafo = net.trafo1ph
    trafo_indices = trafo.index.get_level_values(0).unique()

    for t_idx in trafo_indices:
        t_data = trafo.loc[t_idx]
        if isinstance(t_data, pd.Series):
            t_data = t_data.to_frame().T

        flat = t_data.reset_index() if isinstance(t_data.index, pd.MultiIndex) else t_data

        # Identify buses (HV = lower index, LV = higher index)
        if "bus" in flat.columns:
            bus_values = pd.to_numeric(flat["bus"], errors="coerce").dropna().astype(int).tolist()
        else:
            bus_values = flat.index.get_level_values("bus").astype(int).tolist()
        buses = sorted(set(bus_values))
        if len(buses) < 2:
            continue
        hv_bus, lv_bus = buses[0], buses[1]

        # Determine LV-side connection from to_phase
        if "bus" in flat.columns:
            lv_mask_flat = pd.to_numeric(flat["bus"], errors="coerce").astype(int) == lv_bus
        else:
            lv_mask_flat = flat.index.get_level_values("bus").astype(int) == lv_bus
        lv_to_phases = pd.to_numeric(flat.loc[lv_mask_flat, "to_phase"], errors="coerce").dropna().astype(int)
        if lv_to_phases.empty:
            continue

        lv_is_delta = (lv_to_phases != 0).all()
        if not lv_is_delta:
            continue  # Already Wye — nothing to do

        # Determine HV-side connection for logging
        if "bus" in flat.columns:
            hv_mask_flat = pd.to_numeric(flat["bus"], errors="coerce").astype(int) == hv_bus
        else:
            hv_mask_flat = flat.index.get_level_values("bus").astype(int) == hv_bus
        hv_to_phases = pd.to_numeric(flat.loc[hv_mask_flat, "to_phase"], errors="coerce").dropna().astype(int)
        hv_conn = "D" if (hv_to_phases != 0).all() else "Y"
        old_conn = f"{hv_conn}_D"
        new_conn = f"{hv_conn}_Y"

        # --- Apply changes to the real (multi-indexed) trafo1ph DataFrame ---
        # Build a boolean mask over the full trafo1ph index for this transformer's LV rows
        idx = trafo.index
        level0 = idx.get_level_values(0)  # trafo index
        level1 = idx.get_level_values(1)  # bus
        lv_mask = (level0 == t_idx) & (level1.astype(int) == lv_bus)

        # 1. Set to_phase = 0 (Wye: connect to neutral)
        trafo.loc[lv_mask, "to_phase"] = 0

        # 2. Set from_phase = cycling 1,2,3 per circuit (standard Y group-0)
        n_lv_rows = int(lv_mask.sum())
        y_from_phases = [1, 2, 3] * max(1, n_lv_rows // 3)
        trafo.loc[lv_mask, "from_phase"] = y_from_phases[:n_lv_rows]

        # 3. Divide vn_kv by sqrt(3): Delta stored L-L, Wye stores L-L/sqrt(3)
        trafo.loc[lv_mask, "vn_kv"] = trafo.loc[lv_mask, "vn_kv"].astype(float) / SQRT3

        changes[t_idx] = {"old": old_conn, "new": new_conn}

    return changes


# ── Run across all MC networks and save updated copies ───────────────────────
src_dir = Path(r"networks/mc")
dst_dir = Path(r"networks/mc_xfmr")
dst_dir.mkdir(parents=True, exist_ok=True)

pkl_files = sorted(src_dir.glob("*.pkl"))
total = len(pkl_files)
summary_rows = []

t_start = time.time()
for i, pkl_path in enumerate(pkl_files, 1):
    circuit_key = pkl_path.stem
    t0 = time.time()

    with open(pkl_path, "rb") as fh:
        net = pickle.load(fh)

    changes = update_mc_xfmr_connections(net)

    # Save updated network
    out_path = dst_dir / pkl_path.name
    with open(out_path, "wb") as fh:
        pickle.dump(net, fh)

    for t_idx, info in changes.items():
        summary_rows.append({"CKT_KEY": circuit_key, "TRAFO_IDX": t_idx,
                             "OLD_CONN": info["old"], "NEW_CONN": info["new"]})

    elapsed = time.time() - t0
    total_elapsed = time.time() - t_start
    avg = total_elapsed / i
    eta = avg * (total - i)
    if changes:
        print(f"[{i}/{total}] {circuit_key}: updated {len(changes)} trafo(s) "
              f"({elapsed:.1f}s, ETA {eta:.0f}s)")

total_time = time.time() - t_start
df_changes = pd.DataFrame(summary_rows)
print(f"\nDone in {total_time:.1f}s — {len(df_changes)} transformers updated "
      f"across {total} circuits.")
if not df_changes.empty:
    print("\nChange summary:")
    print(df_changes.groupby(["OLD_CONN", "NEW_CONN"]).size().reset_index(name="COUNT").to_string(index=False))

[1/882] CKT_100_16795: updated 94 trafo(s) (4.0s, ETA 3493s)
[2/882] CKT_1014_17972: updated 41 trafo(s) (0.8s, ETA 2098s)
[3/882] CKT_1019_17995: updated 4 trafo(s) (0.4s, ETA 1500s)
[4/882] CKT_1021_18000: updated 21 trafo(s) (0.4s, ETA 1214s)
[5/882] CKT_1025_18018: updated 22 trafo(s) (0.4s, ETA 1042s)
[6/882] CKT_1029_18017: updated 21 trafo(s) (0.2s, ETA 899s)
[7/882] CKT_1031_18043: updated 6 trafo(s) (0.0s, ETA 774s)
[8/882] CKT_1033_18045: updated 23 trafo(s) (0.3s, ETA 714s)
[9/882] CKT_1040_18076: updated 37 trafo(s) (0.1s, ETA 648s)
[10/882] CKT_1043_18094: updated 3 trafo(s) (0.0s, ETA 584s)
[11/882] CKT_1048_13343: updated 16 trafo(s) (0.3s, ETA 555s)
[12/882] CKT_1051_12960: updated 28 trafo(s) (0.5s, ETA 548s)
[13/882] CKT_1053_12976: updated 7 trafo(s) (0.4s, ETA 529s)
[14/882] CKT_1074_13087: updated 1 trafo(s) (0.0s, ETA 492s)
[15/882] CKT_1093_15603: updated 33 trafo(s) (0.4s, ETA 480s)
[16/882] CKT_1096_15608: updated 1 trafo(s) (0.2s, ETA 458s)
[17/882] CKT_1105_15643: updated 5 trafo(s) (0.2s, ETA 440s)
[18/882] CKT_1106_15646: updated 51 trafo(s) (0.4s, ETA 434s)
[19/882] CKT_1108_15648: updated 28 trafo(s) (0.5s, ETA 432s)
[20/882] CKT_1112_15670: updated 11 trafo(s) (0.3s, ETA 424s)
[21/882] CKT_1114_15680: updated 32 trafo(s) (0.4s, ETA 420s)
[22/882] CKT_1135_18140: updated 58 trafo(s) (0.4s, ETA 416s)
[23/882] CKT_1146_18180: updated 40 trafo(s) (0.3s, ETA 410s)
[24/882] CKT_114_16955: updated 4 trafo(s) (0.1s, ETA 395s)
[25/882] CKT_1152_18222: updated 32 trafo(s) (0.2s, ETA 384s)
[26/882] CKT_115_17030: updated 252 trafo(s) (0.8s, ETA 394s)
[27/882] CKT_1161_13164: updated 20 trafo(s) (0.4s, ETA 392s)
[28/882] CKT_1163_13178: updated 97 trafo(s) (0.5s, ETA 393s)
[29/882] CKT_1173_13253: updated 6 trafo(s) (0.4s, ETA 392s)
[30/882] CKT_1174_13256: updated 43 trafo(s) (0.3s, ETA 385s)
[31/882] CKT_1181_13310: updated 28 trafo(s) (0.3s, ETA 380s)
[32/882] CKT_1190_13355: updated 3 trafo(s) (0.2s, ETA 374s)
[33/882] CKT_1200_15715: updated 21 trafo(s) (0.4s, ETA 372s)
[34/882] CKT_1203_15737: updated 17 trafo(s) (0.3s, ETA 370s)
[35/882] CKT_1209_15758: updated 46 trafo(s) (0.3s, ETA 366s)
[36/882] CKT_1213_15865: updated 1 trafo(s) (0.0s, ETA 356s)
[37/882] CKT_1215_15880: updated 20 trafo(s) (0.2s, ETA 351s)
[38/882] CKT_1221_15910: updated 18 trafo(s) (0.1s, ETA 344s)
[39/882] CKT_1224_15922: updated 21 trafo(s) (0.6s, ETA 347s)
[40/882] CKT_1228_15953: updated 1 trafo(s) (0.0s, ETA 339s)
[41/882] CKT_1241_18271: updated 11 trafo(s) (0.2s, ETA 335s)
[42/882] CKT_1245_18295: updated 7 trafo(s) (0.1s, ETA 329s)
[43/882] CKT_1247_18301: updated 14 trafo(s) (0.2s, ETA 325s)
[44/882] CKT_1248_18307: updated 16 trafo(s) (0.5s, ETA 326s)
[45/882] CKT_1253_18330: updated 80 trafo(s) (0.7s, ETA 331s)
[46/882] CKT_1255_18335: updated 15 trafo(s) (1.0s, ETA 342s)
[47/882] CKT_1259_18370: updated 13 trafo(s) (0.4s, ETA 342s)
[48/882] CKT_1269_13386: updated 7 trafo(s) (0.1s, ETA 335s)
[49/882] CKT_1277_13467: updated 13 trafo(s) (0.4s, ETA 335s)
[50/882] CKT_1284_13508: updated 5 trafo(s) (0.3s, ETA 333s)
[51/882] CKT_1289_13538: updated 3 trafo(s) (0.2s, ETA 330s)
[52/882] CKT_1295_13565: updated 40 trafo(s) (0.3s, ETA 328s)
[53/882] CKT_1313_16007: updated 12 trafo(s) (0.1s, ETA 322s)
[55/882] CKT_1321_16030: updated 13 trafo(s) (0.1s, ETA 311s)
[56/882] CKT_1323_16043: updated 11 trafo(s) (0.7s, ETA 315s)
[57/882] CKT_1326_16049: updated 33 trafo(s) (0.2s, ETA 312s)
[58/882] CKT_1330_16073: updated 11 trafo(s) (0.2s, ETA 310s)
[59/882] CKT_133_19655: updated 5 trafo(s) (0.1s, ETA 306s)
[60/882] CKT_1348_18580: updated 18 trafo(s) (0.1s, ETA 302s)
[61/882] CKT_1352_18525: updated 69 trafo(s) (0.7s, ETA 306s)
[62/882] CKT_1363_18610: updated 149 trafo(s) (0.7s, ETA 311s)
[63/882] CKT_136_19670: updated 51 trafo(s) (0.5s, ETA 312s)
[64/882] CKT_1372_18408: updated 61 trafo(s) (0.6s, ETA 314s)
[65/882] CKT_1374_18629: updated 35 trafo(s) (0.8s, ETA 319s)
[66/882] CKT_137_19697: updated 16 trafo(s) (0.3s, ETA 317s)
[67/882] CKT_1381_13610: updated 5 trafo(s) (0.0s, ETA 313s)
[69/882] CKT_1396_13660: updated 45 trafo(s) (0.3s, ETA 307s)
[70/882] CKT_1398_13680: updated 38 trafo(s) (0.2s, ETA 304s)
[71/882] CKT_1400_13695: updated 11 trafo(s) (0.2s, ETA 302s)
[72/882] CKT_1404_13720: updated 5 trafo(s) (0.1s, ETA 299s)
[73/882] CKT_1408_13737: updated 4 trafo(s) (0.5s, ETA 300s)
[74/882] CKT_140_19700: updated 6 trafo(s) (0.1s, ETA 296s)
[75/882] CKT_1419_16122: updated 2 trafo(s) (0.1s, ETA 292s)
[76/882] CKT_1427_16147: updated 29 trafo(s) (0.2s, ETA 290s)
[77/882] CKT_1429_13580: updated 14 trafo(s) (0.3s, ETA 289s)
[78/882] CKT_1435_16200: updated 123 trafo(s) (0.4s, ETA 289s)
[79/882] CKT_1437_16220: updated 28 trafo(s) (0.5s, ETA 291s)
[80/882] CKT_1440_10580: updated 43 trafo(s) (0.4s, ETA 290s)
[81/882] CKT_14428_06451: updated 12 trafo(s) (0.1s, ETA 287s)
[82/882] CKT_1444_16267: updated 25 trafo(s) (0.2s, ETA 285s)
[83/882] CKT_14450_09805: updated 49 trafo(s) (0.3s, ETA 284s)
[84/882] CKT_14460_19586: updated 13 trafo(s) (0.5s, ETA 285s)
[85/882] CKT_14486_03004: updated 17 trafo(s) (0.3s, ETA 284s)
[86/882] CKT_14518_07417: updated 9 trafo(s) (1.0s, ETA 290s)
[87/882] CKT_1458_18674: updated 4 trafo(s) (0.0s, ETA 287s)
[88/882] CKT_1459_18657: updated 4 trafo(s) (0.3s, ETA 286s)
[89/882] CKT_14606_11476: updated 133 trafo(s) (0.5s, ETA 287s)
[90/882] CKT_14611_06530: updated 24 trafo(s) (0.3s, ETA 287s)
[91/882] CKT_14623_16124: updated 1 trafo(s) (0.0s, ETA 283s)
[92/882] CKT_14667_02046: updated 30 trafo(s) (0.8s, ETA 286s)
[93/882] CKT_14669_04784: updated 51 trafo(s) (0.4s, ETA 287s)
[94/882] CKT_14671_09092: updated 13 trafo(s) (0.6s, ETA 288s)
[95/882] CKT_14672_15315: updated 19 trafo(s) (0.6s, ETA 290s)
[96/882] CKT_14725_13892: updated 5 trafo(s) (0.0s, ETA 287s)
[97/882] CKT_1474_18780: updated 29 trafo(s) (0.5s, ETA 287s)
[99/882] CKT_1479_18815: updated 18 trafo(s) (0.1s, ETA 282s)
[100/882] CKT_14848_06201: updated 38 trafo(s) (0.8s, ETA 285s)
[101/882] CKT_1484_18843: updated 1 trafo(s) (0.1s, ETA 282s)
[103/882] CKT_14900_11751: updated 20 trafo(s) (0.3s, ETA 279s)
[104/882] CKT_1492_13758: updated 3 trafo(s) (0.4s, ETA 279s)
[106/882] CKT_14974_11641: updated 17 trafo(s) (0.1s, ETA 274s)
[107/882] CKT_1501_13791: updated 45 trafo(s) (0.6s, ETA 275s)
[108/882] CKT_1502_13795: updated 21 trafo(s) (0.4s, ETA 275s)
[109/882] CKT_1507_13820: updated 41 trafo(s) (0.6s, ETA 277s)
[111/882] CKT_1521_13870: updated 2 trafo(s) (0.3s, ETA 278s)
[112/882] CKT_1532_16308: updated 4 trafo(s) (0.0s, ETA 275s)
[113/882] CKT_1533_16310: updated 67 trafo(s) (1.0s, ETA 279s)
[114/882] CKT_1540_16334: updated 41 trafo(s) (0.4s, ETA 279s)
[115/882] CKT_1547_16352: updated 11 trafo(s) (0.6s, ETA 280s)
[116/882] CKT_1550_16359: updated 33 trafo(s) (0.3s, ETA 280s)
[117/882] CKT_1561_16404: updated 7 trafo(s) (0.7s, ETA 281s)
[118/882] CKT_156_06131: updated 23 trafo(s) (1.4s, ETA 287s)
[119/882] CKT_1570_18871: updated 47 trafo(s) (0.3s, ETA 287s)
[120/882] CKT_1578_18929: updated 4 trafo(s) (0.5s, ETA 287s)
[121/882] CKT_1581_18950: updated 31 trafo(s) (0.3s, ETA 286s)
[122/882] CKT_15_17454: updated 37 trafo(s) (0.3s, ETA 285s)
[123/882] CKT_1611_13930: updated 9 trafo(s) (0.1s, ETA 283s)
[124/882] CKT_1616_13918: updated 17 trafo(s) (0.7s, ETA 284s)
[125/882] CKT_1620_13959: updated 9 trafo(s) (0.2s, ETA 283s)
[126/882] CKT_1621_13960: updated 27 trafo(s) (0.3s, ETA 282s)
[127/882] CKT_1626_13982: updated 8 trafo(s) (0.0s, ETA 280s)
[128/882] CKT_1636_14037: updated 34 trafo(s) (0.4s, ETA 280s)
[129/882] CKT_1637_14047: updated 16 trafo(s) (0.6s, ETA 281s)
[130/882] CKT_1649_16455: updated 6 trafo(s) (0.3s, ETA 280s)
[131/882] CKT_164_06887: updated 17 trafo(s) (0.3s, ETA 279s)
[132/882] CKT_1653_16461: updated 19 trafo(s) (0.2s, ETA 278s)
[133/882] CKT_1658_16472: updated 17 trafo(s) (0.3s, ETA 277s)
[134/882] CKT_165_16112: updated 17 trafo(s) (0.1s, ETA 276s)
[135/882] CKT_1660_16476: updated 7 trafo(s) (0.3s, ETA 275s)
[136/882] CKT_1663_16490: updated 215 trafo(s) (0.9s, ETA 277s)
[137/882] CKT_166_17692: updated 6 trafo(s) (0.2s, ETA 276s)
[138/882] CKT_1674_16535: updated 11 trafo(s) (0.3s, ETA 275s)
[139/882] CKT_1678_16550: updated 32 trafo(s) (0.3s, ETA 275s)
[140/882] CKT_167_03257: updated 13 trafo(s) (0.1s, ETA 273s)
[141/882] CKT_1680_19100: updated 21 trafo(s) (0.2s, ETA 271s)
[142/882] CKT_1685_19133: updated 25 trafo(s) (0.2s, ETA 270s)
[143/882] CKT_1689_19139: updated 33 trafo(s) (0.2s, ETA 269s)
[144/882] CKT_168_12024: updated 38 trafo(s) (0.3s, ETA 268s)
[145/882] CKT_1693_19140: updated 93 trafo(s) (0.4s, ETA 268s)
[146/882] CKT_1695_19150: updated 172 trafo(s) (0.7s, ETA 270s)
[147/882] CKT_169_11022: updated 23 trafo(s) (0.3s, ETA 269s)
[148/882] CKT_16_01377: updated 5 trafo(s) (0.3s, ETA 268s)
[149/882] CKT_1707_19230: updated 22 trafo(s) (0.1s, ETA 266s)
[150/882] CKT_170_07251: updated 6 trafo(s) (0.4s, ETA 266s)
[151/882] CKT_1711_19245: updated 1 trafo(s) (0.3s, ETA 265s)
[152/882] CKT_1718_19268: updated 8 trafo(s) (0.0s, ETA 263s)
[153/882] CKT_171_08161: updated 29 trafo(s) (0.4s, ETA 263s)
[154/882] CKT_1727_14043: updated 8 trafo(s) (0.6s, ETA 264s)
[155/882] CKT_1729_14074: updated 10 trafo(s) (0.3s, ETA 263s)
[156/882] CKT_172_04726: updated 28 trafo(s) (1.0s, ETA 265s)
[157/882] CKT_1731_14082: updated 3 trafo(s) (0.0s, ETA 263s)
[158/882] CKT_173_13082: updated 34 trafo(s) (0.3s, ETA 263s)
[159/882] CKT_1742_14134: updated 10 trafo(s) (0.4s, ETA 263s)
[161/882] CKT_1750_14152: updated 38 trafo(s) (0.9s, ETA 263s)
[162/882] CKT_1753_14154: updated 14 trafo(s) (0.1s, ETA 262s)
[163/882] CKT_175_19176: updated 6 trafo(s) (0.3s, ETA 261s)
[164/882] CKT_1762_14178: updated 34 trafo(s) (0.5s, ETA 261s)
[165/882] CKT_1763_14181: updated 14 trafo(s) (0.2s, ETA 260s)
[166/882] CKT_1776_16585: updated 10 trafo(s) (0.3s, ETA 260s)
[167/882] CKT_1777_16587: updated 2 trafo(s) (0.0s, ETA 258s)
[168/882] CKT_1787_16600: updated 36 trafo(s) (0.9s, ETA 260s)
[169/882] CKT_178_11012: updated 12 trafo(s) (0.3s, ETA 259s)
[170/882] CKT_1793_16665: updated 37 trafo(s) (0.4s, ETA 259s)
[171/882] CKT_1806_19309: updated 14 trafo(s) (0.1s, ETA 257s)
[172/882] CKT_1809_19340: updated 11 trafo(s) (0.0s, ETA 256s)
[173/882] CKT_1812_19354: updated 3 trafo(s) (0.2s, ETA 255s)
[174/882] CKT_1814_19370: updated 25 trafo(s) (0.1s, ETA 254s)
[175/882] CKT_1815_19373: updated 36 trafo(s) (0.4s, ETA 253s)
[176/882] CKT_1824_19417: updated 49 trafo(s) (0.3s, ETA 253s)
[177/882] CKT_1828_19450: updated 36 trafo(s) (0.3s, ETA 252s)
[178/882] CKT_1833_19537: updated 32 trafo(s) (0.6s, ETA 253s)
[179/882] CKT_1835_19528: updated 17 trafo(s) (0.7s, ETA 254s)
[180/882] CKT_1842_19300: updated 26 trafo(s) (0.2s, ETA 253s)
[181/882] CKT_1850_11363: updated 3 trafo(s) (0.3s, ETA 252s)
[182/882] CKT_1854_10333: updated 7 trafo(s) (0.4s, ETA 252s)
[183/882] CKT_1858_15372: updated 10 trafo(s) (0.3s, ETA 251s)
[184/882] CKT_1859_02323: updated 1 trafo(s) (0.1s, ETA 250s)
[185/882] CKT_1860_11041: updated 9 trafo(s) (0.3s, ETA 249s)
[186/882] CKT_1868_04422: updated 35 trafo(s) (0.6s, ETA 250s)
[187/882] CKT_1878_14004: updated 2 trafo(s) (0.2s, ETA 249s)
[188/882] CKT_1879_16763: updated 31 trafo(s) (0.3s, ETA 248s)
[189/882] CKT_1880_19785: updated 47 trafo(s) (0.2s, ETA 247s)
[190/882] CKT_1896_00669: updated 22 trafo(s) (0.4s, ETA 247s)
[191/882] CKT_189_10931: updated 7 trafo(s) (0.2s, ETA 247s)
[192/882] CKT_18_03353: updated 17 trafo(s) (1.0s, ETA 249s)
[193/882] CKT_1905_00695: updated 21 trafo(s) (0.4s, ETA 248s)
[194/882] CKT_1906_00698: updated 21 trafo(s) (0.2s, ETA 247s)
[195/882] CKT_1908_00705: updated 19 trafo(s) (0.5s, ETA 247s)
[196/882] CKT_1909_00720: updated 26 trafo(s) (0.5s, ETA 247s)
[197/882] CKT_1911_00726: updated 8 trafo(s) (0.4s, ETA 247s)
[198/882] CKT_1914_00740: updated 3 trafo(s) (0.2s, ETA 247s)
[199/882] CKT_1948_00927: updated 27 trafo(s) (0.3s, ETA 246s)
[200/882] CKT_1957_00990: updated 117 trafo(s) (1.0s, ETA 248s)
[201/882] CKT_1959_01030: updated 90 trafo(s) (0.5s, ETA 248s)
[202/882] CKT_195_05626: updated 10 trafo(s) (0.1s, ETA 247s)
[203/882] CKT_1960_01040: updated 40 trafo(s) (0.2s, ETA 246s)
[204/882] CKT_1962_01050: updated 25 trafo(s) (0.1s, ETA 245s)
[205/882] CKT_1963_01510: updated 23 trafo(s) (0.2s, ETA 244s)
[206/882] CKT_1964_01053: updated 36 trafo(s) (0.5s, ETA 244s)
[207/882] CKT_196_19261: updated 25 trafo(s) (0.3s, ETA 243s)
[208/882] CKT_197_14709: updated 21 trafo(s) (0.1s, ETA 242s)
[209/882] CKT_2002_01096: updated 1 trafo(s) (0.1s, ETA 241s)
[210/882] CKT_2004_01140: updated 16 trafo(s) (0.1s, ETA 240s)
[211/882] CKT_2018_01231: updated 10 trafo(s) (0.2s, ETA 239s)
[212/882] CKT_2021_01251: updated 27 trafo(s) (0.2s, ETA 238s)
[213/882] CKT_2023_01255: updated 10 trafo(s) (0.3s, ETA 238s)
[214/882] CKT_2025_17258: updated 13 trafo(s) (1.4s, ETA 240s)
[215/882] CKT_2037_00805: updated 50 trafo(s) (0.4s, ETA 240s)
[216/882] CKT_2039_00814: updated 12 trafo(s) (0.2s, ETA 239s)
[217/882] CKT_2041_00816: updated 17 trafo(s) (0.1s, ETA 238s)
[218/882] CKT_2045_00830: updated 43 trafo(s) (0.3s, ETA 238s)
[219/882] CKT_2053_00870: updated 21 trafo(s) (0.4s, ETA 237s)
[220/882] CKT_2055_00878: updated 19 trafo(s) (0.4s, ETA 237s)
[221/882] CKT_2063_11843: updated 71 trafo(s) (0.3s, ETA 237s)
[222/882] CKT_2074_11907: updated 14 trafo(s) (0.4s, ETA 236s)
[223/882] CKT_2079_11915: updated 69 trafo(s) (0.6s, ETA 237s)
[224/882] CKT_2080_11920: updated 42 trafo(s) (0.4s, ETA 237s)
[225/882] CKT_2082_11931: updated 21 trafo(s) (0.2s, ETA 236s)
[226/882] CKT_2083_11935: updated 28 trafo(s) (0.2s, ETA 235s)
[227/882] CKT_2093_11975: updated 7 trafo(s) (0.2s, ETA 234s)
[228/882] CKT_209_14375: updated 48 trafo(s) (0.3s, ETA 234s)
[229/882] CKT_2107_12058: updated 2 trafo(s) (0.3s, ETA 233s)
[230/882] CKT_2109_12070: updated 45 trafo(s) (0.3s, ETA 233s)
[231/882] CKT_210_14376: updated 15 trafo(s) (0.2s, ETA 232s)
[232/882] CKT_2112_12083: updated 40 trafo(s) (0.3s, ETA 231s)
[233/882] CKT_2116_12100: updated 34 trafo(s) (0.2s, ETA 231s)
[234/882] CKT_2120_12131: updated 5 trafo(s) (0.3s, ETA 230s)
[235/882] CKT_2127_12159: updated 7 trafo(s) (0.3s, ETA 230s)
[236/882] CKT_2132_12175: updated 13 trafo(s) (0.4s, ETA 229s)
[237/882] CKT_2135_12198: updated 5 trafo(s) (0.5s, ETA 230s)
[238/882] CKT_2141_12243: updated 18 trafo(s) (0.2s, ETA 229s)
[240/882] CKT_2155_12331: updated 29 trafo(s) (0.4s, ETA 227s)
[241/882] CKT_2163_12395: updated 32 trafo(s) (0.5s, ETA 227s)
[242/882] CKT_2169_12425: updated 33 trafo(s) (0.7s, ETA 228s)
[243/882] CKT_2170_12430: updated 21 trafo(s) (0.4s, ETA 228s)
[244/882] CKT_217_14397: updated 10 trafo(s) (0.3s, ETA 227s)
[246/882] CKT_218_14401: updated 8 trafo(s) (0.5s, ETA 227s)
[247/882] CKT_2194_12564: updated 21 trafo(s) (0.4s, ETA 226s)
[248/882] CKT_2198_12582: updated 14 trafo(s) (0.4s, ETA 226s)
[249/882] CKT_2200_12600: updated 35 trafo(s) (0.2s, ETA 225s)
[250/882] CKT_2204_12616: updated 7 trafo(s) (0.3s, ETA 225s)
[251/882] CKT_2210_12690: updated 226 trafo(s) (1.0s, ETA 226s)
[252/882] CKT_2211_12700: updated 15 trafo(s) (0.2s, ETA 225s)
[253/882] CKT_2219_12716: updated 21 trafo(s) (0.1s, ETA 224s)
[254/882] CKT_2226_16240: updated 8 trafo(s) (0.2s, ETA 223s)
[255/882] CKT_2248_08360: updated 38 trafo(s) (0.4s, ETA 223s)
[256/882] CKT_2251_01518: updated 9 trafo(s) (0.2s, ETA 222s)
[257/882] CKT_2267_10417: updated 22 trafo(s) (0.4s, ETA 222s)
[258/882] CKT_226_14436: updated 11 trafo(s) (0.2s, ETA 221s)
[259/882] CKT_2282_09320: updated 17 trafo(s) (0.7s, ETA 222s)
[260/882] CKT_2287_04045: updated 26 trafo(s) (0.4s, ETA 222s)
[261/882] CKT_2290_08949: updated 112 trafo(s) (0.8s, ETA 222s)
[262/882] CKT_2292_10360: updated 32 trafo(s) (0.5s, ETA 222s)
[263/882] CKT_2298_01744: updated 18 trafo(s) (0.4s, ETA 222s)
[264/882] CKT_229_14450: updated 25 trafo(s) (0.5s, ETA 222s)
[265/882] CKT_2301_08405: updated 121 trafo(s) (0.6s, ETA 222s)
[266/882] CKT_2305_02600: updated 2 trafo(s) (0.0s, ETA 221s)
[267/882] CKT_2306_03990: updated 16 trafo(s) (0.2s, ETA 221s)
[268/882] CKT_2307_04980: updated 23 trafo(s) (0.3s, ETA 220s)
[269/882] CKT_2308_05190: updated 30 trafo(s) (0.4s, ETA 220s)
[270/882] CKT_2309_07370: updated 31 trafo(s) (0.8s, ETA 221s)
[271/882] CKT_2315_04795: updated 7 trafo(s) (0.3s, ETA 220s)
[272/882] CKT_2316_05502: updated 22 trafo(s) (0.1s, ETA 219s)
[273/882] CKT_2317_06108: updated 3 trafo(s) (0.2s, ETA 218s)
[274/882] CKT_2319_01846: updated 5 trafo(s) (0.4s, ETA 218s)
[275/882] CKT_2339_03090: updated 10 trafo(s) (0.1s, ETA 217s)
[276/882] CKT_2340_10500: updated 156 trafo(s) (0.7s, ETA 217s)
[277/882] CKT_2342_01960: updated 114 trafo(s) (0.6s, ETA 217s)
[278/882] CKT_2343_02490: updated 81 trafo(s) (0.5s, ETA 217s)
[279/882] CKT_2344_02640: updated 176 trafo(s) (0.6s, ETA 218s)
[280/882] CKT_2345_10420: updated 103 trafo(s) (0.4s, ETA 217s)
[281/882] CKT_2352_01810: updated 75 trafo(s) (0.3s, ETA 217s)
[282/882] CKT_2353_02370: updated 94 trafo(s) (0.3s, ETA 216s)
[283/882] CKT_2354_05310: updated 102 trafo(s) (0.5s, ETA 216s)
[284/882] CKT_2355_08510: updated 69 trafo(s) (0.2s, ETA 216s)
[285/882] CKT_2356_03680: updated 126 trafo(s) (0.5s, ETA 216s)
[286/882] CKT_2357_04160: updated 77 trafo(s) (0.3s, ETA 215s)
[287/882] CKT_2358_08750: updated 78 trafo(s) (0.3s, ETA 215s)
[288/882] CKT_2359_11720: updated 91 trafo(s) (0.3s, ETA 214s)
[289/882] CKT_2360_01350: updated 25 trafo(s) (0.3s, ETA 214s)
[290/882] CKT_2361_02510: updated 71 trafo(s) (0.6s, ETA 214s)
[291/882] CKT_2362_07346: updated 10 trafo(s) (0.2s, ETA 213s)
[292/882] CKT_2363_01629: updated 39 trafo(s) (0.4s, ETA 213s)
[293/882] CKT_2380_07900: updated 5 trafo(s) (0.0s, ETA 212s)
[294/882] CKT_2381_04723: updated 51 trafo(s) (0.4s, ETA 212s)
[295/882] CKT_2382_06504: updated 6 trafo(s) (0.5s, ETA 212s)
[296/882] CKT_2388_10600: updated 14 trafo(s) (0.1s, ETA 211s)
[297/882] CKT_2403_05307: updated 43 trafo(s) (0.3s, ETA 210s)
[298/882] CKT_2404_07490: updated 46 trafo(s) (0.5s, ETA 210s)
[299/882] CKT_2405_09355: updated 9 trafo(s) (0.1s, ETA 209s)
[300/882] CKT_2410_09443: updated 2 trafo(s) (0.3s, ETA 209s)
[301/882] CKT_2412_05810: updated 165 trafo(s) (0.9s, ETA 210s)
[302/882] CKT_2414_04770: updated 178 trafo(s) (0.8s, ETA 210s)
[303/882] CKT_2415_05360: updated 46 trafo(s) (0.4s, ETA 210s)
[304/882] CKT_2416_02730: updated 91 trafo(s) (0.3s, ETA 210s)
[305/882] CKT_2417_04000: updated 92 trafo(s) (0.3s, ETA 209s)
[306/882] CKT_2422_02026: updated 17 trafo(s) (0.2s, ETA 209s)
[307/882] CKT_2427_09703: updated 13 trafo(s) (0.3s, ETA 208s)
[308/882] CKT_242_16890: updated 10 trafo(s) (0.3s, ETA 208s)
[309/882] CKT_2443_03688: updated 17 trafo(s) (0.5s, ETA 207s)
[310/882] CKT_2458_02424: updated 10 trafo(s) (0.1s, ETA 207s)
[311/882] CKT_2459_02540: updated 81 trafo(s) (0.6s, ETA 207s)
[312/882] CKT_245_16925: updated 15 trafo(s) (1.0s, ETA 207s)
[313/882] CKT_2460_03390: updated 7 trafo(s) (0.0s, ETA 206s)
[314/882] CKT_2461_03875: updated 12 trafo(s) (0.1s, ETA 205s)
[315/882] CKT_2462_03944: updated 12 trafo(s) (0.1s, ETA 205s)
[316/882] CKT_2463_08940: updated 57 trafo(s) (0.2s, ETA 204s)
[317/882] CKT_2464_09580: updated 34 trafo(s) (0.3s, ETA 204s)
[318/882] CKT_2465_10435: updated 13 trafo(s) (0.1s, ETA 203s)
[319/882] CKT_2466_05600: updated 38 trafo(s) (0.2s, ETA 202s)
[320/882] CKT_2467_10873: updated 72 trafo(s) (0.3s, ETA 202s)
[321/882] CKT_2468_02845: updated 49 trafo(s) (0.5s, ETA 201s)
[322/882] CKT_2470_03170: updated 80 trafo(s) (0.5s, ETA 201s)
[323/882] CKT_2473_04890: updated 69 trafo(s) (0.3s, ETA 201s)
[324/882] CKT_2474_05400: updated 67 trafo(s) (0.3s, ETA 200s)
[325/882] CKT_2475_07240: updated 243 trafo(s) (0.9s, ETA 201s)
[326/882] CKT_2476_08240: updated 57 trafo(s) (0.4s, ETA 201s)
[327/882] CKT_2477_11730: updated 214 trafo(s) (0.7s, ETA 201s)
[328/882] CKT_2479_04530: updated 53 trafo(s) (0.5s, ETA 201s)
[329/882] CKT_247_16926: updated 5 trafo(s) (0.2s, ETA 200s)